### ISSUE TITLE
company submission form claims successful submission even when it wasn't successful

### ISSUE THREAD

**Issue by Nothing4You** [datenanfragen/website#1]
Hi,
if the request to submit a new company fails in the background the site is still claiming it was submitted successfully:
> Your contribution has been sent successfully. Thank you once again! We will now review it as soon as possible

This can easily be reproduced by installing uMatrix, which in default configuration doesn't allow requests to third party domains.

**Comment by baltpeter** [comment]
Hi,

thank you very much for the report!

We do indeed seem to display the success modal even in case of an error (https://github.com/datenanfragen/website/blob/master/src/suggest-edit.js#L123) for some reason. That really shouldn't be the case.

Unfortunately, we won't be able to POST the data to the same origin as the website is designed as a static page but we should at least give the user some proper notice of what went wrong.

Cheers,
Benjamin

**Comment by baltpeter** [comment]
This should be fixed in 3aa3f81, waiting for review by @zner0L.

**Comment by baltpeter** [comment]
The fix is now (finally) live.
