### ISSUE TITLE
Format the dates in the "My requests" table

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#100]
On the "My requests" page, the dates are currently formatted as an ISO 8601 string. While I personally absolutely prefer that date format, many users probably won't be used to it. Instead, we should format the date.

The way to go here is probably the [`toLocaleDateString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString) function. 

Some notes:

* Don't use the browser's locale but instead our internal one. You can access it using the global variables `globals.country` for the country and `LOCALE` (wrongly named) for the language.
* Pass the following options: `{ weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }`

![image](https://user-images.githubusercontent.com/4048809/66235734-4b2fd700-e6e0-11e9-840a-3e68b4caebd9.png)

**Comment by ggangix** [comment]
I would like to take this issue.

**Comment by baltpeter** [comment]
Please do, thank you!
