### ISSUE TITLE
Why does resetRequestToDefault always use English if not language is passed?

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#1010]
While working on #1008, I stumbled across this:

https://github.com/datenanfragen/website/blob/18192edfcac895536899b6b8be0ebe6fb2d41b5b/src/store/request.ts#L270

Why is the progression `language` -> `REQUEST_FALLBACK_LANGUAGE`? Shouldn't we use the website language instead of `REQUEST_FALLBACK_LANGUAGE`? Why would we set the default request language to `en` for non-English sites?

**Comment by zner0L** [comment]
You are right, I don't know where it went wrong, but this should default to `inferRequestlanguage()`, I mean, that’s the whole purpose of this function, isn’t it?
