### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by milotype** [datenanfragen/website#1066]
For some reason many strings in the Croatian version of the website "https://www.osobnipodaci.org/" do not translate.

Please inspect what's wrong, because the Croatian version of the website used to work.

**Comment by baltpeter** [comment]
Thank you for the report. Can you please try again? I don't think I can reproduce the issue anymore. I'm guessing that we just hadn't merged all your recent contributions yet (but have now).

**Comment by milotype** [comment]
@baltpeter Everything seems to work again for Croatian. Thank you.
