### ISSUE TITLE
Rename the IdData class

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/website#107]
Currently, a lot of things in our code are called "id data". As this is confusing we would like to have the name of the `src/Utilities/IdData` class refactored to `SavedIdData`. Please look thoroughly through the code and test it to check if the old name is still used anywhere.

**Comment by robflop** [comment]
I'll look into this.

**Comment by zner0L** [comment]
Cool, thank you! Let me know when you have any questions :)

**Comment by robflop** [comment]
I've got a question then:

Should _every_ instance of IdData (including ``id-data`` and its variations) be renamed to ``SavedIdData`` (and ``saved-id-data`` etc, respectively) or should only direct references to the mentioned class be changed?

Specific example:

[src/id-data-controls Line 130](https://github.com/datenanfragen/website/blob/master/src/id-data-controls.js#L130), which uses a ``custom_id_data`` variable. Should this be changed to ``custom_saved_id_data``?

**Comment by zner0L** [comment]
No, there are cases when "id data" makes sense as a name from context. The class is just adding to the confusion (as you can see it also got you :D), so please only rename all mentions of the class.

**Comment by robflop** [comment]
Will do, thank you for explaining.

**Comment by robflop** [comment]
Reminder to close this issue as the PR is merged.

**Comment by zner0L** [comment]
Thanks for the reminder and making the PR :)
