### ISSUE TITLE
Move the request storing to UserRequests

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/website#108]
Currently, requests are just stored by calling `Request::store()` which directly accesses the storage. I would like only one class to make direct access to the storage: `UserRequests`, which acts like a wrapper for all request storing related stuff – apparently except the storing itself. So todos from this issue include:

 - [ ]  Create a method to store requests in `UserRequests`, e.g. `UserRequests::storeRequest()`. The logic for this is mostly already done in `Request::store()`.
 - [ ] Replace the code inside of `Request::store()` with a one- or twoliner that references the new method of `UserRequests`, similar to [this line](https://github.com/datenanfragen/website/blob/169eccdd1e818d0da6ba359c7e33a6fb1de5d5f2/src/Components/RequestGeneratorBuilder.js#L85).

**Comment by haridevelops** [comment]
can i have a look in to it ?

**Comment by prajwalMR** [comment]
I would like to give this a shot

**Comment by prajwalMR** [comment]
#112
