### ISSUE TITLE
Tutorial at generator page step 1/4

### ISSUE THREAD

**Issue by marcelosantos89** [datenanfragen/website#136]
At the generator page when it's showing the tutorial

![image](https://user-images.githubusercontent.com/5165063/66875886-afd41700-efa7-11e9-8839-105e7a379e87.png)

It says on the right but the box is on the left.
I found the file to facilitate the fix. (good first issue for someone)

**website/src/i18n/en.json**
Line 319: `"request-parameters": "<p>Alright, let’s start generating your requests. We will try our best to make this as easy as possible for you.</p><p>On the right, we have already prefilled the contact details for the first company.</p>"`

I think it should have a class to show different strings
One for On the Left (Desktop) and one for On the Top (Mobile / Tablet)
Something like

`<p class="desktop">On the left, we have already prefilled the contact details for the first company.</p><p class="mobile">On top, we have already prefilled the contact details for the first company.</p>`

**Comment by baltpeter** [comment]
Good catch, thank you! I have added the appropriate labels. If anyone wants to pick this up, feel free. :)

**Comment by luko0610** [comment]
I'll take that if it's still available.

**Comment by baltpeter** [comment]
It is, thanks.

**Comment by luko0610** [comment]
Maybe you can help me on how to get the request generator to show the tutorial.

**Comment by luko0610** [comment]
Need some help. hugo server --disableFastRender only displays a blank page for me.

**Comment by luko0610** [comment]
Okay, I found it out.

**Comment by baltpeter** [comment]
As future reference to everyone else: The tutorial is only shown when the generator is accessed from the wizard on the homepage.

**Comment by luko0610** [comment]
Yes, I have found that out. Can you tell me where the text inside the wizard is actually defined?

**Comment by baltpeter** [comment]
The actual translations for the tutorial are here ([German](https://github.com/datenanfragen/website/blob/master/src/i18n/de.json#L311) and [English](https://github.com/datenanfragen/website/blob/master/src/i18n/en.json#L312)) as @marcelosantos89 pointed out.

The tutorial code is defined [here](https://github.com/datenanfragen/website/blob/master/src/wizard-tutorial.js). It is initialized [here](https://github.com/datenanfragen/website/blob/master/src/generator.js#L54).

If you are talking about the homepage wizard, that is defined [here](https://github.com/datenanfragen/website/blob/master/src/Components/Wizard.js) and the translations are [here](https://github.com/datenanfragen/website/blob/master/src/i18n/de.json#L229).

**Comment by luko0610** [comment]
Thanks for the help, I think I can complete this today.

**Comment by luko0610** [comment]
I fixed it and made a pull request. #139

**Comment by baltpeter** [comment]
Feel free to signup to our Hacktoberfest event to get some stickers from us, if you want: https://www.datarequests.org/blog/hacktoberfest-2019/

**Comment by luko0610** [comment]
Great! I'll do that.
