### ISSUE TITLE
Remove the .txt replacer

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/website#144]
Before datenanfragen/data#244 was fixed, we had `.txt` file extensions for custom templates in the database that we removed in the generator again. All occurrences of this can now be removed. They are all marked with `TODO` comments and should look something like this: `.replace(/\.txt$/, '')`

**Comment by themayurkumbhar** [comment]
Hi @zner0L 
i would like to take this one.
is it just removing existing `.txt` from files under companies json files?
