### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by NathanBnm** [datenanfragen/website#148]
Hi! I recently translated the whole website into French on Weblate, but I haven't the rights to validate my own translation. Could you check please?

I left a few comments too. Can you please have a look on it?

Otherwise I'm glad to contribute to this project. I think it can be a very useful tool. If there is anything I can do to help more let me know. You may be interested in adding data for France, as the French translation will be available.

**Comment by baltpeter** [comment]
Wow, thank you very much for the translations! I have just answered the questions a moment ago but hadn't seen the suggestions yet—I'll definitely need to look into Weblate some more.

If you want, I can also add you to the Weblate project. I have some basic understanding of French from school but having an actual native speaker to look over other users' suggestions would of course be ideal.

We have also recently merged our translation files from two different systems into one, so there's some new strings to translate. We would of course appreciate if you could take a look at those, too. Perfectly fine if you don't want to, though. :)

Finally, we are currently running a [Hacktoberfest event](https://www.datarequests.org/blog/hacktoberfest-2019/). This is 'officially' only meant for contributions through GitHub but for such a useful and big contribution, we'll gladly make an exception. We'd love to send you some stickers as a small token of appreciation, if you want.

Let me know if I've missed anything!

**Comment by NathanBnm** [comment]
@baltpeter you're welcome 😄 

Sure it would be great if you do this! I often check on Weblate.

I saw that the translation files were new on Weblate. That's  part of why I wanted to contribute too (many projects aren't maintained anymore). I will look into this once you'll have added me to the project if you still want to.

I have just read your blog post. That would be nice, thank you. How do you want to contact me? I have a contact form on my website page if you want (link on my profile). I'll answer you then.

**Comment by baltpeter** [comment]
> Sure it would be great if you do this! I often check on Weblate.

Awesome, just added you.

> How do you want to contact me?

It would be best if you just also registered through our [hacktoberfest@datenanfragen.de](mailto:hacktoberfest@datenanfragen.de?subject=Registration%20for%20Hacktoberfest%202019&body=I%20want%20to%20participate%20in%20the%20Hacktoberfest%202019%20event%20by%20Datenanfragen.de%20e.%20V.%0A%0AGitHub%20user%20name%3A%20%5Bplease%20fill-in%5D%0A%0AI%20have%20read%20the%20conditions%20of%20participation%20and%20privacy%20policy%20(https%3A%2F%2Fwww.datarequests.org%2Fblog%2Fhacktoberfest-2019)%20and%20accept%20these%20conditions.) email, that would make managing the registrations easiest for us.

Two more questions, if you don't mind:

1. I noticed you used 'vous' instead of 'tu' for the translations. For the German translations, we decided on informal pronouns instead of formal ones to achieve a more friendly and close tone with our users. What do you think is more appropriate in French?

2. We have different domains for the different language versions of the website. With a French version soon to come, any suggestions for a nice `.fr` domain that is essentially a translation of the `datarequests` would be much appreciated.

**Comment by NathanBnm** [comment]
>
> Awesome, just added you.
> 
Thank you :smile:
>
> It would be best if you just also registered through our [hacktoberfest@datenanfragen.de](mailto:hacktoberfest@datenanfragen.de?subject=Registration%20for%20Hacktoberfest%202019&body=I%20want%20to%20participate%20in%20the%20Hacktoberfest%202019%20event%20by%20Datenanfragen.de%20e.%20V.%0A%0AGitHub%20user%20name%3A%20%5Bplease%20fill-in%5D%0A%0AI%20have%20read%20the%20conditions%20of%20participation%20and%20privacy%20policy%20(https%3A%2F%2Fwww.datarequests.org%2Fblog%2Fhacktoberfest-2019)%20and%20accept%20these%20conditions.) email, that would make managing the registrations easiest for us.
>
I'll do that!

>     1. I noticed you used 'vous' instead of 'tu' for the translations. For the German translations, we decided on informal pronouns instead of formal ones to achieve a more friendly and close tone with our users. What do you think is more appropriate in French?
>
I didn't know this intention, because there is no difference in english. I think it is more common to use "vous" in French. It is more respectful to users. For my part, "vous" is more appropriate in French because the use of "tu" makes things less reliable in my opinion.

I can be wrong, but I think that for a website, using "tu" hasn't the real same effect than in germany I guess.

>     2. We have different domains for the different language versions of the website. With a French version soon to come, any suggestions for a nice `.fr` domain that is essentially a translation of the `datarequests` would be much appreciated.
>
This is something hard because `datarequest.org` or `datenanfragen` means `demande de données` in French and I think it's looking weird.

I was thinking about something like `mesdonnees.fr` which means `mydata`but it already exists.
I still have to think about it.

**Comment by NathanBnm** [comment]
Finally I changed my mind 😅 

It could be great if the french domain was `demandetesdonnees.fr`.
Or maybe `demande-tes-donnees.fr` for more readabilty?

With this domain it's better to use `tu` instead of `vous`. And either with one or another, it wil be consistent if adopted on all the site so there is no real problem here.

**Comment by baltpeter** [comment]
> I didn't know this intention, because there is no difference in english.

Yeah, that is a (lack of a) feature that I certainly envy the English language for. :D Makes things much easier.

> With this domain it's better to use tu instead of vous. And either with one or another, it wil be consistent if adopted on all the site so there is no real problem here.

I'll defer to your expertise here. Whatever you think sounds better.

> It could be great if the french domain was demandetesdonnees.fr.  
> Or maybe demande-tes-donnees.fr for more readabilty?

I've discussed this with @zner0L and we both like the suggestion. We've registered both domains now. I'm also not quite sure which one we should use as the primary one. I am leaning towards `demande-tes-donnees.fr`, though.

---

By the way: We have a Matrix channel specifically for the internationalization of the project. Currently, there's just @zner0L and me there but it's a good place for discussions on this subject (especially ones that don't have a separate issue). Feel free to join, if you have a Matrix account: `#dade-i18n:matrix.altpeter.me`

**Comment by NathanBnm** [comment]
Sorry I haven't a Matrix account 😅

**Comment by NathanBnm** [comment]
@baltpeter I updated French translation on Weblate. Now everything is using `tu`. I just need to ask you to answer to the comments I left. There are a few strings I don't know how to translate because of a lack of context. Thank you in advance 😄

**Comment by baltpeter** [comment]
Huge thanks once again!

And sorry, I hope I caught all comments this time—I think I replied to the comments in the wrong language the last time. Let me know if there are still any responses missing.

Yes, the domain should indeed be replaced with the one specific to the language.

**Comment by NathanBnm** [comment]
Everything is fine know 👍
