### ISSUE TITLE
id-data heading padding

### ISSUE THREAD

**Issue by davenewham** [datenanfragen/website#156]
The formatting on the Rectification request input field on the right handside for "My data" heading seems a little off. Seems like the correct padding is needed after the input field?

It is more prevelant in non-mobile resolutions. 

![grafik](https://user-images.githubusercontent.com/15076177/67279336-14710380-f4cb-11e9-8983-0d792ff28087.png)

**Comment by baltpeter** [comment]
Thanks for the report!

Should be easy enough to fix, so I'll leave that for someone else.

**Comment by parammittal16** [comment]
@baltpeter can I do this ?

**Comment by baltpeter** [comment]
This was fixed in #316.
