### ISSUE TITLE
"Your GDPR Rights" link broken on German site

### ISSUE THREAD

**Issue by davenewham** [datenanfragen/website#163]
Clicking "Weiterlesen..." button on front page of German site redirects to 404 as it links to "https://www.datenanfragen.de/blog/your-gdpr-rights" instead of "https://www.datenanfragen.de/blog/deine-dsgvo-rechte/"

**Comment by baltpeter** [comment]
Thanks for the report.

Interestingly enough, `blog/your-gdpr-rights` is set as an alias for the post but that doesn't seem to work.
