### ISSUE TITLE
Fix RSS support for Datenanfragen.de blog

### ISSUE THREAD

**Issue by m-rey** [datenanfragen/website#173]
Currently, https://www.datenanfragen.de/blog/ has no RSS support (afaik).
A rss/atom feed is an easy way to stay updated using a feed reader.

**Comment by baltpeter** [comment]
I'm definitely a proponent of RSS as well. We do have an RSS feed at: https://www.datenanfragen.de/index.xml

While not exposed in the UI anywhere, it is specified in the meta tags:

```html
<link href=https://www.datenanfragen.de/index.xml rel=alternate type=application/rss+xml title=Datenanfragen.de>
<link href=https://www.datenanfragen.de/index.xml rel=feed type=application/rss+xml title=Datenanfragen.de>
```

I believe most feed readers should recognize that if you just enter the URL of the blog (or even the homepage for that matter).

**Comment by baltpeter** [comment]
Actually, on further inspection: That feed is empty.

However https://www.datenanfragen.de/blog/index.xml does seem to have the blog posts.

So, there's definitely a bug here that we'll have to investigate. Thanks for reporting!

**Comment by HoffmannP** [comment]
So there are two possible solutions. The one will link to the index.xml of each folder as `.RSSLink` might have done. Might, b/c `.RssLink` is [deprecated](https://gohugo.io/variables/page/) now.

But I think you'd rather want to link to the one RSS-feed for blog articles. That's what I've changed the current version to.

I post the alternative for completeness:

    <link href="{{ with .OutputFormats.Get "RSS" }}{{ .Permalink }}{{ end }}" rel="feed" type="application/rss+xml" title="{{ .Site.Title }}" />

Attached you find the difference for several pages:

```bash
index.html
48:<link href="https://www.datenanfragen.de/blog/index.xml" rel="alternate" type="application/rss+xml" title="Datenanfragen.de" />
49:<link href="https://www.datenanfragen.de/index.xml" rel="feed" type="application/rss+xml" title="Datenanfragen.de" />

blog/index.html
48:<link href="https://www.datenanfragen.de/blog/index.xml" rel="alternate" type="application/rss+xml" title="Datenanfragen.de" />
49:<link href="https://www.datenanfragen.de/blog/index.xml" rel="feed" type="application/rss+xml" title="Datenanfragen.de" />

blog/hacktoberfest-2019/index.html
52:<link href="https://www.datenanfragen.de/blog/index.xml" rel="alternate" type="application/rss+xml" title="Datenanfragen.de" />
53:<link href="" rel="feed" type="application/rss+xml" title="Datenanfragen.de" />

categories/index.html
50:<link href="https://www.datenanfragen.de/blog/index.xml" rel="alternate" type="application/rss+xml" title="Datenanfragen.de" />
51:<link href="https://www.datenanfragen.de/categories/index.xml" rel="feed" type="application/rss+xml" title="Datenanfragen.de" />
```

**Comment by baltpeter** [comment]
@HoffmannP Yeah, always linking to the feed for the blog definitely sounds like the way to go. Thanks!
