### ISSUE TITLE
Bug: Saved signature is overridden on reset

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/website#182]
In the generator, if the signature for the request is reset the blank signature is also save as the saved signature. This behavior is counter intuitive IMO. The expected behavior would be for the current request to have a blank signature field and the saved signature should be kept, if the reset button is clicked in the generator, but the saved signature is overridden, if the reset button is clicked on the saved id data page.

**Comment by merelj** [comment]
I'll try to take a look at it on the weekend, must have set `isEmpty` wrong somewhere :(
