### ISSUE TITLE
Match format of generated JSON on suggestion page and company-json-generator

### ISSUE THREAD

**Issue by m-rey** [datenanfragen/website#187]
This is a nice-to-have proposal. Feel free to put it deep down the backlog.

When a user adds a suggestion on https://www.datenanfragen.de/suggest, the generated JSON differs from the generated JSON of https://github.com/datenanfragen/company-json-generator.
Specifically, on the former, the slug is at the end, while on the latter it's at the beginning.

I would suggest to move the slug of the generated JSON of https://www.datenanfragen.de/suggest to the beginning, as order of the company-json-generator form items is mostly aligned with the generated JSON.

**Comment by baltpeter** [comment]
To explain why this happens: The JSON on the suggest page is also generated through the json-forms library, just like in the company JSON generator.

However, on the suggest page, we don't expose the `slug` field to the user. Instead, we guess a slug *after* the JSON has been generated:

https://github.com/datenanfragen/website/blob/f857edf8ce73fe62ec13e4635060e9eb712fac87/src/suggest-edit.js#L138-L145

It should be possible to add the slug at the beginning instead. If someone wants to take a look at that, please feel free!

---

In the meantime, to propose a workaround: When reviewing suggestions, I just always click the *Edit* link in the issue which open the suggestion in the company JSON generator. Re-exporting it from there also fixes the order of the properties.
