### ISSUE TITLE
"Direct Marketing Objection" generator generates "null" as subject

### ISSUE THREAD

**Issue by m-rey** [datenanfragen/website#189]
In the "Direct Marketing Objection" generator, when trying to generate an objection, the subject is set to `null`.
(In the case of email, the `mailto:` link begins with `mailto:?subject=null (My reference: 2019-xxxxxx)&body=xxxxxxxxxxxxxxxxxx`, where x is a placeholder.)

It apparently doesn't matter if English or German is used to generate the objection.
It apparently also doesn't matter what company/organisation the objection is generated for.
All other generators seem to work as intended.

**Comment by zner0L** [comment]
Hm. While reviewing I also realized we don't have a way to disable features that do not work in other languages. We need a procedure to work around that.
