### ISSUE TITLE
Suche funktioniert nicht

### ISSUE THREAD

**Issue by pyfisch** [datenanfragen/website#194]
Unternehmen werden nicht gefunden (z.B. Amazon), obwohl sie offensichtlich in der Datenbank enthalten sind.

![grafik](https://user-images.githubusercontent.com/2781017/68895536-c5189e80-0729-11ea-8268-d8ca0878c003.png)

**Comment by baltpeter** [comment]
Ich vermute, dass das mit #193 zusammenhängt: Die Suche ist länderabhängig, und wird wahrscheinlich fehlschlagen, wenn kein Land gesetzt ist.

Das könnten wir u. U. ein bisschen more gracefully handlen, indem wir in so einem Fall einfach auf `all` zurückfallen. Thoughts, @zner0L?

**Comment by zner0L** [comment]
Ja, Fallback auf `all` ergibt Sinn würde ich sagen.

**Comment by baltpeter** [comment]
Wenn #197 funktioniert, sollte das dann doch nicht mehr nötig sein. Dann müssten wir nämlich eh in jedem Fall ein Land gesetzt haben.
