### ISSUE TITLE
Broken redirection after credit card donation

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/website#211]
After donating via credit card the JS redirects to the wrong `thanks` page.

**Comment by baltpeter** [comment]
Could you clarify what you mean by the 'wrong' thanks page? Is there more than one?

**Comment by baltpeter** [comment]
Ah, the URL is wrong.

**Comment by zner0L** [comment]
It redirects to `datarequests.org/thanks?donation_reference[donation_reference]` which takes you to a 404 page.
