### ISSUE TITLE
Create "Contributors" page

### ISSUE THREAD

**Issue by NathanBnm** [datenanfragen/website#231]
Would be great to have somewhere to credits contributors on the website and maybe in this repo too.
It could be separated between "Developers", "Translators" etc.

**Comment by baltpeter** [comment]
I absolutely agree.

We _do_ currently have the [AUTHORS](https://github.com/datenanfragen/website/blob/master/AUTHORS) file and I think we should build on that.  
This file is currently only a list of names of contributors without any more details (like your grouping into developers, translators, etc.). I wouldn't mind keeping it that way as it saves us from having to translate the descriptions. However, if you or other people think that this distinction would be necessary/helpful, we can certainly look into changing the format. What do you think?

Once we have decided on a format for the AUTHORS file, I can look into including it in the website.

**Comment by baltpeter** [comment]
Oh sorry, I don't get any notifications about those emoji reactions to comments. I'll go ahead and view them as approvals. :D

**Comment by baltpeter** [comment]
I have created a draft in #274, let me know what you think.

Also, anyone who contributed: Feel free to start adding your name to the list, if you want!
