### ISSUE TITLE
Bring accentued letters together on company database page

### ISSUE THREAD

**Issue by NathanBnm** [datenanfragen/website#245]
I noticed that there were some companies starting with Ö but they are displayed after Z.

I guess it could happen with other accentued letters. I think each accentued letter should be interpreted as the normal one. You could use the following correspondance table (non exhaustive).

```
A = Å, Á, À, Â, Ä, Ã
E = É, È, Ê, Ë
I = Ì, Í, Î, Ï
O = Ò, Ó, Ô, Õ, Ö, Ø
U = Ŭ, Ù, Ú, Û, Ü
Y = Ý, Ÿ
C = Ç
N = Ñ
```

**Comment by rgroves** [comment]
If you'd like, I can pick this one up and begin working on it.

Do you have any preference as to how you want this tackled? If it can be implemented by changing only the `company\list.html` template would that be fine? Or should there be a more complex process that will normalize the characters in the name and store it as a key in the company's json file? The former might make the template a little messy but require no changes to the deploy process. The latter would probably simplify the changes needed in the template but would add the complexity to the deploy script.

**Comment by baltpeter** [comment]
Thanks @rgroves, I'll assign you.

It would be best if this could be implemented entirely in the Hugo template. This tends to get fairly messy (as the template already is :D) but it should be possible.  
I would definitely like to avoid needing more work per company in the deploy script as that already takes quite a long time to run.

Other than that, I think the table provided by @NathanBnm should be sufficient. It would be great if you could sort all other characters not covered by that under #. But if that's not possible or too much work, that's also fine.
