### ISSUE TITLE
Broken link for "Read more" on French homepage

### ISSUE THREAD

**Issue by NathanBnm** [datenanfragen/website#250]
The "Read more" button is redirecting to the following page : https://www.demandetesdonnees.fr/blog/your-gdpr-rights instead of https://www.demandetesdonnees.fr/blog/tes-droits-rgpd

**Comment by baltpeter** [comment]
That URL is currently hardcoded [here](https://github.com/datenanfragen/website/blob/master/layouts/index.html#L103). I see two options:

* Either make that URL a translatable string as we've done in some of the other cases.
* Or simply add `your-gdpr-rights` as an alias to the French page.

**Comment by NathanBnm** [comment]
Maybe it's better to make it a translatable string for more consistency (as you said it has already been done in other cases).
