### ISSUE TITLE
SEO: Description in search engines results

### ISSUE THREAD

**Issue by NathanBnm** [datenanfragen/website#266]
It seems that the homepage does not have any description meta tag, so the description displayed in search engines like Google is not very relevant. See these screenshots for [datarequests.org](https://www.datarequests.org/) and [demandetesdonnees.fr](https://www.demandetesdonnees.fr/):

![image](https://user-images.githubusercontent.com/45366162/76141973-32e62e80-6069-11ea-96e2-e2f4861ef374.png)

![image](https://user-images.githubusercontent.com/45366162/76141971-2c57b700-6069-11ea-8abc-3113114f80bf.png)

**Comment by baltpeter** [comment]
Actually, we *do* have meta description tags for the homepage (and any other page that specifies a `description` in the Hugo front matter):

![image](https://user-images.githubusercontent.com/4048809/76142012-5e651b00-6061-11ea-8ea3-108184132d30.png)

If I remember correctly, most search engines just ignore that though and generate their own blurb based on what they think is more relevant to the user's query. I don't have a source on hand for that but I can look it up if you want.

**Comment by NathanBnm** [comment]
Well I didn't see it. But this is strange, Google seems to have changed their rules. Just a few weeks ago it was still using the description meta tag (I just checked on my personnal portfolio). I guess they've been doing that since they changed the presentation of search results. Apparently the displayed description is an excerpt of the first text content on the page.

Maybe we can add a css-hidden paragraph containing the description on top of the page in order to search engines to see it? But the fact is that it will be a bad thing for accessibilty because screen readers will see it too.

Dicussion is open

**Comment by zner0L** [comment]
Google doesn't like repeating descriptions ([see here](https://support.google.com/webmasters/answer/35624?hl=en)). Since most of the content on our website are the company database entries, which do not have a description, I guess Google penalizes the whole website for that. I do not like adding a css-hidden description on top of the page, that is especially bad for screen readers and search engines don't like that very much either.

**Comment by baltpeter** [comment]
> Since most of the content on our website are the company database entries, which do not have a description, I guess Google penalizes the whole website for that.

It might be worth trying to generate descriptions for the company database entries. From the page you linked:

> **Programmatically generate descriptions.** […] For larger database-driven sites, like product aggregators, hand-written descriptions can be impossible. In the latter case, however, programmatic generation of the descriptions can be appropriate and are encouraged.

> **Include clearly tagged facts in the description.** The meta description doesn't just have to be in sentence format; it's also a great place to include information about the page. For example, news or blog postings can list the author, date of publication, or byline information. […] For example, the following meta description provides detailed information about a book.
>
>`<meta name="Description" content="Written by A.N. Author, 
Illustrated by V. Gogh, Price: $17.99, 
Length: 784 pages">`

The company database exposes most of its content through schema.org data anyway but adding that shouldn't be too hard.

**Comment by baltpeter** [comment]
Interestingly enough, Google *does* sometimes seem to actually use our structured data:

![image](https://user-images.githubusercontent.com/4048809/79133532-b3e8c200-7d9b-11ea-846c-3610cdff3b72.png)
