### ISSUE TITLE
Follow ISO language codes recommandations

### ISSUE THREAD

**Issue by NathanBnm** [datenanfragen/website#270]
Languages code for German, English and French are currently formatted like this: "de-de", "en-us" and "fr-fr". I think it should be respectively "de-DE", "en-US" and "fr-FR" as the first two letters refers to the language code and the two others to the country code. Generally the country code should be in uppercase.

I don't think the country code is necessary for countries where the language comes from. For example "fr" stands for French (France) in any case even if not written "fr-FR". However "fr-CA" stands for French (Canada). Same example with "pt" for Portuguese (Portugal) and "pt-BR" for Portuguese (Brazil). But it can be more consistent to always write the full language code and so it can stay like this!

**Comment by baltpeter** [comment]
> Languages code for German, English and French are currently formatted like this: "de-de", "en-us" and "fr-fr".

I have to admit I am not sure where that is the case. Could you clarify that?

In JS, the structure is currently as follows:

* We have a variable `globals.country` holding the country as either the two-letter lowercase ISO country code or `all`.
* And we have the variable `LOCALE` holding the two-letter ISO language code. Now, admittedly that name is far from ideal as the *locale* is actually supposed to hold both the country and language as you describe. I would call that legacy code from before we were interested in the user's country. :D

**Comment by NathanBnm** [comment]
Here is the config file where I noticed that: https://github.com/datenanfragen/website/blob/master/config/_default/languages.toml.

I assume we will have some trouble if we have to differ some languages with their respective spoken country if we do not respect these recommendations. I'm thinking about `pt` and `pr-BR` which I saww the most.

Is that clear enough? Don't really know what to explain more about it x)

**Comment by baltpeter** [comment]
Ah ok. Those `languageCode`s are only used to set the language in the HTML ([here](https://github.com/datenanfragen/website/blob/master/layouts/_default/baseof.html#L2) and [here](https://github.com/datenanfragen/website/blob/master/layouts/partials/head/meta.html#L48). We don't actually rely on them internally.

I guess we can change the format here but it shouldn't make much of a difference.
