### ISSUE TITLE
Also display license information for events

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#324]
This is a [follow-up](https://github.com/datenanfragen/website/pull/312#discussion_r424526239) from #312.

Just like our regular blog posts, the [events](https://github.com/datenanfragen/website/blob/2130c1bdcdd3a4f994b2c0c0add3da93a73237d1/content/en/verein/event/okl-berlin-05-2020.md) also have a `license` field in the frontmatter. This information needs to be displayed on the actual page.

This is already implemented in the `_default` single template:

https://github.com/datenanfragen/website/blob/2130c1bdcdd3a4f994b2c0c0add3da93a73237d1/layouts/_default/single.html#L27-L31

It just needs to be added to the [`event` single template](https://github.com/datenanfragen/website/blob/master/layouts/event/single.html).

**Comment by haardikdharma10** [comment]
Hey @baltpeter, i'd like to trigger this as well. Can you assign me this?
