### ISSUE TITLE
Donation via bank transfer allows negative values

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#326]
If you copy-paste a negative number into the donate form at https://www.datarequests.org/donate/  you can still procceed with *bank transfer*. The other payment methods raise an error.

**Comment by baltpeter** [comment]
Thanks for letting us know!

This is a fairly non-critical issue that seems like a great first issue, so I'll leave it for someone else to work on. We've also recently done something similar in  #301, so that can serve as a guide.

**Comment by medeasyJsr** [comment]
hey @baltpeter, I would like to help with this issue

**Comment by baltpeter** [comment]
Sure, thank you!

Let me know if you have any questions.

**Comment by kumar80** [comment]
Hey @baltpeter , I am working on this issue wanted to know if there should be any flash messages if yes what would be it

**Comment by baltpeter** [comment]
Yes, a flash message would be good, @kumar80. You can use the same one as in #301 (see [here](https://github.com/datenanfragen/website/pull/301/files#diff-17b99fa8e6c12a09b25fbadc543db4f9R296)).
