### ISSUE TITLE
Broken image on act-page

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#329]
https://www.datenanfragen.de/act/drk-brandenburg-datenleck/

The image https://www.datenanfragen.de/act/img/drk-brandenburg-datenleck.jpg doesn't load on my machine.

**Comment by m-rey** [comment]
Thanks for the report.
The image path is wrong, I'll submit a PR.

**Comment by m-rey** [comment]
Some blog posts also have this issue, btw.
