### ISSUE TITLE
Use modern image formats with Hugo

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#373]
Google PageSpeed (rightfully) complains that we are not making use of [modern image formats](https://web.dev/uses-webp-images/):

![image](https://user-images.githubusercontent.com/4048809/91093425-f1faca00-e648-11ea-9b19-88a9a3f8af98.png)

While we could manually convert and use them, that would be very time consuming and easy to forget, especially since Hugo already [supports converting images automatically](https://gohugo.io/content-management/image-processing/). Unfortunately though, [Hugo doesn't support any modern image format like WebP yet](https://github.com/gohugoio/hugo/issues/5924). :(

If that is supported one day, we should absolutely [make use](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#Use_modern_image_formats_boldly) of such a feature.

Note that we can unfortunately not completely switch to WebP yet as [browser support](https://caniuse.com/webp) isn't sufficient. We still need to support the legacy formats using srcset, similar to what I did in #372.

**Comment by rahulsunil2** [comment]
I've fixed this, [Pull Request](https://github.com/datenanfragen/website/pull/415)

**Comment by baltpeter** [comment]
A quick note for everyone: As I said, we are **not** looking for manual conversions, only automatic ones as part of our Hugo build.

This issue cannot be resolved until support for that is added in Hugo.

**Comment by chrysillala** [comment]
Hi, can I try to fix this issue? Thanks

**Comment by baltpeter** [comment]
> Hi, can I try to fix this issue? Thanks

Please see my above comment: https://github.com/datenanfragen/website/issues/373#issuecomment-702612156

**Comment by baltpeter** [comment]
Looks like we can finally tackle this soon: https://github.com/gohugoio/hugo/pull/8397

**Comment by opncow** [comment]
From looking at the code of gohugoio/hugo#8397 I cannot tell: Will it be possible to convert e.g. JPEG images to webp automatically during the image processing? That would be neat!

**Comment by baltpeter** [comment]
> Will it be possible to convert e.g. JPEG images to webp automatically during the image processing? That would be neat!

That's my understanding, yes (see also: https://github.com/gohugoio/hugo/issues/5924).
