### ISSUE TITLE
Allow webmanifest in CSP

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#399]
When loading the site in Chrome, the following error is logged to the console:

> Refused to load manifest from 'https://www.datenanfragen.de/site.webmanifest' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'manifest-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by Techievena** [comment]
@baltpeter I want to work on this

**Comment by baltpeter** [comment]
Sure, I'll assign you.
