### ISSUE TITLE
Update the open-source page

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#407]
Our [open-source overview](https://www.datarequests.org/open-source/) has become quite outdated, we should update it! 

* We no longer use `yace` but [backend](https://github.com/datenanfragen/) which atm handles comments, suggestions, donations, and hacktoberfest registrations
* There are other (new) repos, such as media, letter-generator, and locate-contacts-addon, should we include these as well?

**Comment by baltpeter** [comment]
`media` and `letter-generator` should definitely be included. I wouldn't include locate-contacts-addon as it is pretty much abandoned unless someone else picks it up. 

As for `backend`: I would only list comments, suggestions and donations as examples. The Hacktoberfest stuff seems fairly inconsequential and I don't want to have to update the page whenever we add a new feature. :D

**Comment by michizhou** [comment]
Hi, @baltpeter @mal-tee. I can definitely take on this issue. Can I go ahead?

**Comment by mal-tee** [comment]
Sure 👍
