### ISSUE TITLE
Content Security Policy directive Violation Error in Chrome

### ISSUE THREAD

**Issue by khanna98** [datenanfragen/website#412]
The following error appears in the Chrome dev console when loading the website:

<img width="731" alt="Screenshot 2020-10-02 at 12 30 21 AM" src="https://user-images.githubusercontent.com/29047276/94851779-87f2f300-0446-11eb-990e-20f37559cf01.png">

**Comment by khanna98** [comment]
This issue is resolved. 😊 
Please review and merge #413 for this issue. 👍🏻

**Comment by baltpeter** [comment]
Thanks for raising this issue!

Unfortunately, #413 doesn't actually fix it. I'll open this issue for everyone but feel free to give it another go. :)

**Comment by zner0L** [comment]
Isn't this a duplicate of #399?

**Comment by baltpeter** [comment]
Good point. Forgot about that one. :D
