### ISSUE TITLE
Nicer event titles in the ics export

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#422]
The .ics export is a very handy feature, but I like to have an overview over my calendar without clicking on events.
In this case the title could be more precise:

![grafik](https://user-images.githubusercontent.com/45886910/94941503-3f364b00-04d5-11eb-99f3-d7b1f1dd6753.png)
![grafik](https://user-images.githubusercontent.com/45886910/94941547-4eb59400-04d5-11eb-97c5-391d8b22306b.png)

As you can see there is only one request due.

I would like to have the companies name in the title of the event (this is called `SUMMARY` in the .ics). This might even work for a few companies at once (depending on the length?). For more we could show a count in the title.

This is where the magic happens:

https://github.com/datenanfragen/website/blob/1aed9ca5644e92e90d2a3bbf4f1593d16348f497/src/my-requests.js#L361

**Comment by king-11** [comment]
Hey @mal-tee can I start working on this?

**Comment by mal-tee** [comment]
Sure, go ahead!

**Comment by king-11** [comment]
@mal-tee sorry for the delay but am not able to test the website locally the docs aren't very clear can you help out a bit, please

**Comment by king-11** [comment]
thanks a lot @mal-tee I was really confused now I will start working on this issue you can hope for a pr soon will try my best

**Comment by mal-tee** [comment]
Great, have fun coding 👍

**Comment by king-11** [comment]
@mal-tee so shall I pass in instead of 'ics-summary' as new variable whose value will be set as per the number of requests if I guess 2 companies is good so if we have two companies then there recipients else the count how does that sound .

https://github.com/datenanfragen/website/blob/1aed9ca5644e92e90d2a3bbf4f1593d16348f497/src/my-requests.js#L361

**Comment by mal-tee** [comment]
Sounds good
