### ISSUE TITLE
Wrap everything main in <main>

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/website#427]
We basically wrap everything in main already. I'd like to keep it that way, especially since this becomes meaningful with #426. I don't know where this is needed (so you'd need to do some research), but one page I found was https://datarequests.org/id-data-controls.

**Comment by jadonwolffs** [comment]
Can I give this a go for Hacktoberfest?

**Comment by GoGi2712** [comment]
Can I work on this issue?

**Comment by jonahcrowlinson** [comment]
> Can I give this a go for Hacktoberfest?

> Can I work on this issue?

@jadonwolffs @GoGi2712 - if you can fix this issue, then fix the issue. Unless it says different in the Code of Conduct or CONTRIBUTING.md there is no need to ask if you can fix it. Just make sure to link the issue in a pull request using #ISSUE_ID.

**Comment by zner0L** [comment]
We'll, I hope you don't both started working on this. This is not a competition. I'll assign @jadonwolffs, as they were the first to ask. Also: asking is not needed, but appreciated @jonahcrowlinson.
