### ISSUE TITLE
Runing without updating dependencies and sequential instruction local dev

### ISSUE THREAD

**Issue by king-11** [datenanfragen/website#431]
README.md tells to run 
```bash 
yarn
``` 
to install dependencies but that will as per yarn's default lead to an update of packages which can lead to breaking change update or lock file upgrade which can prevent proper merging of PRs . change it to 
```bash
yarn --frozen-lockfile
```
instead, also updating readme.md to ensure that the instruction for local deployment are written down in a sequential order which i myself encountered as of now can be a bit confusing

**Comment by baltpeter** [comment]
The [docs](https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install) say the following:

> If `yarn.lock` is present and is enough to satisfy all the dependencies listed in `package.json`, the exact versions recorded in `yarn.lock` are installed, and `yarn.lock` will be unchanged. Yarn will not check for newer versions.

Seems like this should be fine for us.

**Comment by king-11** [comment]
@baltpeter ohh cool i will close the issue and sorry i didn't go through docs properly

**Comment by king-11** [comment]
@baltpeter i recently tried but i guess there is some issue the dependencies get upgraded on running only yarn

**Comment by baltpeter** [comment]
Thanks for following up.

I cannot reproduce this problem with this repo:

![image](https://user-images.githubusercontent.com/4048809/95674285-a2437400-0b9e-11eb-8d6b-b489ecfd2a27.png)

The docs say that upgrades can occur if "`yarn.lock` [is] not enough to satisfy all the dependencies listed in `package.json` (for example, if you manually add a dependency to `package.json`)". Maybe that's the case with the repo you tried? We make sure to always keep our `yarn.lock` up to date.

Nevertheless, it might still be a good idea to implement this. What do you think, @zner0L?

**Comment by king-11** [comment]
@zner0L any updates if the issue doesn't seem like a good one shall i close it? 😅
