### ISSUE TITLE
Privacy controls: Only set cookie if preference != default

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#432]
We are saving the user preferences for our [privacy controls](https://www.datarequests.org/privacy-controls) as cookies. Currently, we always set the cookie if the user changes something. However, this isn't necessary.

If a preference is set back to the default value, we can just delete the cookie.

The relevant code is here:

https://github.com/datenanfragen/website/blob/05133ee1ee4d147c1cf643cde8161291e300332c/src/Utility/Privacy.js#L39-L41

Note how the default value is determined:

https://github.com/datenanfragen/website/blob/05133ee1ee4d147c1cf643cde8161291e300332c/src/Utility/Privacy.js#L35

**Comment by ayush015** [comment]
@baltpeter Can I take a look ?

**Comment by baltpeter** [comment]
Sure, @ayush015. I'll assign you.

**Comment by ayush015** [comment]
@baltpeter how can I set it up ? if you can help me that'd be great

**Comment by abhishekUpmanyu** [comment]
@baltpeter Hi! I have made the necessary change, can you please assign this to me, I'm looking forward to contribute

**Comment by baltpeter** [comment]
@ayush015 Are you still working on this? If so, we'll wait for your PR. Otherwise, I'll review the one by @abhishekUpmanyu.

**Comment by ayush015** [comment]
nope I way busy somewhere else .
