### ISSUE TITLE
Only set changed_saved_companies cookie if the user actually changed something

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#433]
In the wizard on the homepage, we use the `changed_saved_companies` cookie to determine whether the user has changed the default suggested companies (to test, use Germany, Austria or the UK as the country; we only have suggested companies for them). However, this cookie is unnecessarily set whenever the user enters the homepage.

Instead, we should set the cookie only if the user actually changed something. The cookie should not be set if the user just loads the homepage. In addition, it should instead be deleted whenever we currently set it to `false`.

The relevant code is in this file: https://github.com/datenanfragen/website/blob/master/src/Components/Wizard.js

**Comment by alejandrotoga02** [comment]
Hi , I would like to take it

**Comment by baltpeter** [comment]
@alejandrotoga02 Sure, thanks!
