### ISSUE TITLE
Wizard: Re-focus search bar after selecting a company

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#435]
In the wizard on our homepage, users can add companies through the search bar:

![Peek 2020-10-10 14-47](https://user-images.githubusercontent.com/4048809/95655435-cb102e80-0af6-11eb-904e-43cb16002827.gif)

When adding many companies (which is what the wizard is for, after all), it would be a lot more convenient if the search bar was re-focused after selecting a company.

**Comment by sumirart** [comment]
hey @baltpeter can I work on this? thanks

**Comment by baltpeter** [comment]
@sumirart Sure, thanks!

**Comment by zner0L** [comment]
Closing this in favor of #649
