### ISSUE TITLE
Translate the changes from #411 into German and French (and the whole page into Portuguese)

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#436]
In #411, @michizhou kindly updated our open source page. These changes also need to be reflected in the German and French translations.

In addition, it would be great to have a Portuguese translation of the whole page

**Comment by Devanshh** [comment]
Hi @baltpeter , Can I take this up!?

**Comment by baltpeter** [comment]
@Devanshh If you speak one of the languages, sure. But please note that we cannot accept machine translations.

**Comment by Devanshh** [comment]
Well, if that's the case, Can I add the translations for Hindi?(If required) Because Hindi is my native language. I studied basic German in high school.

**Comment by baltpeter** [comment]
Sorry, we don't offer our website in Hindi, so there is no need for this translation.

**Comment by debPhoenix** [comment]
I can translate in French. I'm a french native! :)

**Comment by baltpeter** [comment]
@debPhoenix Perfect, thanks!

**Comment by rafaeelaudibert** [comment]
I can work on translating the page to (Brazilian) Portuguese!
