### ISSUE TITLE
StarWidget for ratings in comments is not shown anymore

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#437]
On the company pages, users can leave comments and also, optionally, rate the company they are commenting on. The ratings should be shown as "stars" to the right of the user's name but for some reason, they aren't anymore.

Take [Humble Bundle](https://www.datarequests.org/company/humblebundle) for example. If we look at the [comments JSON](https://backend.datenanfragen.de/comments/get/en/company/humblebundle), we see that there should be one comment with a rating of 5 stars:

```json
[
  {
    "id": "VO4rR76Oiggfuw02nED2m",
    "author": "Benni",
    "message": "I received by data via email within two weeks.",
    "target": "en/company/humblebundle",
    "additional": "{\"rating\":\"5\"}",
    "accept_token": "G8U4PzOfOWuPLqvbAhHoF",
    "is_accepted": 1,
    "added_at": "2020-10-10T10:35:19.311Z"
  }
]
```

However, the rating is not shown on the website:

![image](https://user-images.githubusercontent.com/4048809/95656012-e2e9b180-0afa-11eb-9006-1348210536b7.png)

This is the relevant code:

https://github.com/datenanfragen/website/blob/05133ee1ee4d147c1cf643cde8161291e300332c/src/Components/CommentsWidget.js#L74-L84

**Comment by rezziemaven** [comment]
Hi @baltpeter! I don't mind taking a stab at this one if you don't mind assigning it to me! By the way, do you happen to have a screenshot showing what the rating looked like when it did appear? Or is it only just a matter of tweaking the code to see if it appears again?

**Comment by baltpeter** [comment]
Sure @rezziemaven, I have assigned you, thanks!

I unfortunately don't have a screenshot on hand, but the styling should all still be there.

**Comment by rezziemaven** [comment]
Awesome, thank you! Will get to it :)

**Comment by shinnlok** [comment]
Hi all,

While analyzing https://github.com/datenanfragen/website/issues/438, I found that the backend response format was somewhat unexpected. If merged, I think https://github.com/datenanfragen/backend/pull/20 should fix this. Sorry @rezziemaven if you were already looking into it.

**Comment by rezziemaven** [comment]
Hey @shinnlok! It would be great if it fixes it! I guess @baltpeter would let me know if it does or not.

**Comment by baltpeter** [comment]
I can confirm that datenanfragen/backend#20 fixes this issue, so I'll close it.

Thanks for your help, @rezziemaven and @shinnlok!
