### ISSUE TITLE
Calculate and show aggregate ratings for companies

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#438]
The companies in our [company database](https://www.datarequests.org/company) can be rated by users.

Currently, we only display the ratings next to the comments. [Note that there is currently a bug (#437) with that.] In addition, we should also calculate and show aggregate ratings. These should also be exposed as [structured data](https://developers.google.com/search/docs/data-types/review-snippet) for search engines.

**Comment by shinnlok** [comment]
@baltpeter Can I take a look?

**Comment by baltpeter** [comment]
@shinnlok Sure, I'll assign you.
