### ISSUE TITLE
Need help to run app - dont know how to run a development environment

### ISSUE THREAD

**Issue by lestgabo** [datenanfragen/website#468]
**What is the expected behaviour?**
where is the localhost? I cant find any port, url, listening or anything
how do I open the app?

**Please mention other relevant information.**
I am a noob with Preact and Hugo...

### It would be great if someone could help with a step by step tutorial.
I have installed Hugo and Preact CLI, ran `deploy.sh`, then ran `yarn dev` but thats it. webpack is watching. But where? where the is it watching? 🥴🥴🥴

please help im so confused

**Comment by baltpeter** [comment]
Hi @lestgabo,

the development procedure is described in the [README](https://github.com/datenanfragen/website#development). You don't need Preact CLI. But in addition to `yarn dev`, you also need to run `hugo server`. The site will then be served on localhost, ports 1313, 1314, 1315 and 1316 for the different language versions.

**Comment by lestgabo** [comment]
thanks @baltpeter!!
