### ISSUE TITLE
Improve text on /suggest

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#474]
Atm. /suggest links to https://github.com/datenanfragen/data/issues, but it should link to https://github.com/datenanfragen/data/pulls. 

I would also like to introduce some hint on the suggest page that we prefer the address of the DPO instead of the regular address. What do you think about that @baltpeter ?

**Comment by mal-tee** [comment]
Tbf the tooltip already asks for privacy-related entries, but I would like to make that more prominent as we get several `suggest`s in `data` that only use the "Impressum".

**Comment by baltpeter** [comment]
As per our discussion, I agree that it might be useful to include some more details for advanced users who want to dig in deeper and make our life easier (always greatly appreciated! :D). Some things to note:

* The idea behind the suggest feature is definitely that _anyone_ can contribute without any preparation/learning required. Even suggestions just including a company name is ok. So, we need to make sure that this is clearly marked as optional and not too prominent.
* There is already quite a bit (too much) text on the suggest page. Ideally, we don't want to make that even worse.

An idea we came up with (not sure yet if this is the ideal solution): Maybe we could have a `<details>` tag containing the additional introduction to our guidelines that is hidden by default and clearly labels the content as optional.
