### ISSUE TITLE
Search won't show "Tier Mobility GmbH"

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#490]
We recently added Bird, Tier, and Voi in datenanfragen/data#822 .

But the search won't display Tier, but shows e.g. Voi.

Tier won't show up with any prefix of this search: 
![grafik](https://user-images.githubusercontent.com/45886910/98440184-8d072a00-20f7-11eb-9777-38556c638f2c.png)

Voi is returned without problems:

![grafik](https://user-images.githubusercontent.com/45886910/98440202-b4f68d80-20f7-11eb-9bbb-3341915261ab.png)

This was on datenanfragen.de Deutsch/Deutschland

**Comment by baltpeter** [comment]
The file is in the wrong folder. :D 

https://github.com/datenanfragen/data/blob/4e0d0f885e7e4418e978c07d90aa40c13f7c0c4f/tier-mobility.json
