### ISSUE TITLE
Generator crash with invalid parameter (unusable report window)

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#497]
- visit https://www.datenanfragen.de/generator#!company=datenanfragen,facebook

**Comment by baltpeter** [comment]
I think https://www.datenanfragen.de/generator#!company=invalidcompany is a better example that doesn't suggest that specifying multiple companies for `#!company` should work. :D

**Comment by mal-tee** [comment]
Note: The variant with a comma seems to render two error windows. `invalidcompany`only one. :D

**Comment by baltpeter** [comment]
I think they both produce the two error modals most of the time but `datenanfragen,facebook` seems more reliable. :D

**Comment by mal-tee** [comment]
`datenanfragen, facebook` also produces a crash. Understandable, but I would prefer if we could `trim` the values.

**Comment by baltpeter** [comment]
Well, the parameter wasn't really designed to be used manually by humans. :D But sure, we can do that.

**Comment by baltpeter** [comment]
Invalid companies now show a flash message instead of breaking the site: https://www.datarequests.org/generator#!company=invalidcompany

And https://www.datarequests.org/generator#!companies=schufa,%20facebook just works. So this fixed.
