### ISSUE TITLE
Signature field (in ID data controls) scrolls while trying to write on it

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#498]
The signature field on https://www.datarequests.org/id-data-controls behaves very awkwardly on mobile:

If you try to write on it, you scroll on the webpage, making it useless. Besides you can't draw longer horizontal lines.

**Comment by baltpeter** [comment]
Interestingly, we had a PR last year that improved the UI of the signature input on mobile:

https://github.com/datenanfragen/website/pull/119

**Comment by mal-tee** [comment]
Can you double check on your mobile device?

**Comment by baltpeter** [comment]
I am **most** excited to announce that this works absolutely flawlessly in Firefox! :D In Chrome-based browser (the DuckDuckGo one, in this case), it works OK but not great (it twitches around a little while writing).

Firefox:

![ScreenRecord-2020-11-08-14-52-23](https://user-images.githubusercontent.com/4048809/98466966-b2b13380-21ca-11eb-8f45-a703219dd601.gif)

Chrome:

![ScreenRecord-2020-11-08-14-53-42(1)](https://user-images.githubusercontent.com/4048809/98466990-d7a5a680-21ca-11eb-9ac9-7203749a7210.gif)

**Comment by baltpeter** [comment]
The built-in browser on Android also works just fine:

![ScreenRecord-2020-11-08-15-03-00](https://user-images.githubusercontent.com/4048809/98467100-7cc07f00-21cb-11eb-847d-abfba31b955b.gif)

**Comment by mal-tee** [comment]
Weird, Firefox and Chrome behave similar on my device. So maybe it's just my phone?

**Comment by baltpeter** [comment]
Also works just fine in Safari on iOS:

![video-2020-11-08-15-11-46](https://user-images.githubusercontent.com/4048809/98467300-754da580-21cc-11eb-8d63-ef605a837b40.gif)

@mal-tee Which browser did you test with?

**Comment by mal-tee** [comment]
Firefox 82.1.1 & Chrome 86.0.4240.185 on Android 10

**Comment by mal-tee** [comment]
Update: Seems like only the field on /id-data-controls is affected.

**Comment by baltpeter** [comment]
![ScreenRecord-2020-11-09-14-50-13](https://user-images.githubusercontent.com/4048809/98549744-23bc1e00-2293-11eb-9750-4001f84be8e6.gif)
