### ISSUE TITLE
Consider lazy loading images

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#502]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/loading

**Comment by king-11** [comment]
@baltpeter can we considering using some library for this :thinking: ?

**Comment by baltpeter** [comment]
@king-11 That shouldn't be necessary and I also don't think the trade-off is worth it. We don't really need lazy loading as we only have a couple of images on our site. We are only considering that as the new `loading` API is now supported widely enough in browsers.

And browsers that don't support `loading` yet will just fall back to the default behaviour, which is fine.

**Comment by king-11** [comment]
So we just have to add the loading attribute in all the img elements that we are using in site

**Comment by baltpeter** [comment]
Well, the goal behind this issue is mostly to discuss evaluate whether that is a good idea. But yes, if we do decide to implement this, it should be as simple as that.
