### ISSUE TITLE
CSP error prevents PDF download from loading on Safari

### ISSUE THREAD

**Issue by fm** [datenanfragen/website#538]
**OS & Browser details:**
macOS Big Sur 11.1 (20C69)
Safari 14.0.2 (16610.3.7.1.9)

<img width="1813" alt="Screen Shot 2021-01-24 at 4 06 19 PM" src="https://user-images.githubusercontent.com/3654256/105643479-1b20c000-5e5e-11eb-9187-87697f30ff1f.png">

Could not replicate on Chrome nor Firefox

**Comment by baltpeter** [comment]
Thanks for reporting this.

From the error message, fixing this should be as simple as adding `'self'` to `child-src`. I'll open a PR.
