### ISSUE TITLE
Suggest: Sort relevant countries list alphabetically

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#551]

**Comment by mal-tee** [comment]
Maybe all lists, e.g. the german categories aren't sorted either.

**Comment by Cool-Runningz** [comment]
Hello! Would you be able to provide a screenshot of which countries list(s) still need to be sorted alphabetically? I tried looking throughout the website and they all looked to be sorted correctly.

If this issue is still open and available, I am interested in helping out. Thanks!

**Comment by baltpeter** [comment]
@Cool-Runningz Oh sorry, I wasn't very clear in the issue description (or lack thereof).

This is the page we are talking about: https://www.datarequests.org/suggest/

**Comment by Cool-Runningz** [comment]
@baltpeter Thank you for clarifying! I will start looking at the work and will reach back out if I have further questions.
