### ISSUE TITLE
Address

### ISSUE THREAD

**Issue by milotype** [datenanfragen/website#576]
I do not understand the hint about addressing at: https://github.com/datenanfragen/website/blob/master/content/en/suggest.md

```
We prefer the contact details of a data protection officer over the regular contact details of a company.

    c/o External Data Protection Officer Ltd.
    Example road 1
    12345 City
    Germany

You can see our preferred address format above: Separate lines with line breaks, do not include the company name and add the country as the last line.
```

You specify, that _company name_ shouldn't be included. IMO, _company name_ **is needed**. A postal address for companies often isn't unique, because companies often share the same address with other companies/residents within a building.

So my suggestion is to use the following example (used in Croatia):
```
    Company name
    c/o Data Protection Officer
    Example road 1
    12345 City
    Country
```
Translators could switch positions of `Company name` and `c/o Data Protection Officer` if needed.

**Comment by baltpeter** [comment]
We definitely agree that the company name has to be included when addressing a letter. The hint you mentioned is only talking about the "address" field in our suggest form, though. The name has to be entered separately in the "name" field.

When constructing the address, our software then automatically prepends the name.

See the record for our association for example.  The address is specified without our name:

https://github.com/datenanfragen/data/blob/a6b04ca12462bc089b41610bca3f480d7866e46f/companies/datenanfragen.json#L17

And the name is specified separately:

https://github.com/datenanfragen/data/blob/a6b04ca12462bc089b41610bca3f480d7866e46f/companies/datenanfragen.json#L9

Whenever we show the address on our website (like on the [company detail page](https://www.datarequests.org/company/datenanfragen)), though, we automatically add the name:

![image](https://user-images.githubusercontent.com/4048809/116078186-d2a7b700-a685-11eb-921b-a3909d1dbf73.png)

That's what the hint is about. If you also added 'Datenanfragen.de e. V.' to the address, the website would show:

> Datenanfragen.de e. V.  
> Datenanfragen.de e. V.  
> Attn: Data Protection  
> Schreinerweg 6  
> 38126 Braunschweig  
> Deutschland

**Comment by milotype** [comment]
Thank you for the explantion ...
