### ISSUE TITLE
Hugo won't build on windows due to filenames: Alias "de/e.v."

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#581]
I tried to build the page with native windows tools instead of WSL and ran into this issue:

```
PS D:\coding\dade\website> hugo server
Start building sites …
ERROR 2021/04/29 11:24:34 Alias "de/e.v." contains component with a trailing space or period, problematic on Windows
Built in 3163 ms
Error: Error building site: cannot create "de/e.v.": Windows filename restriction
```

**Comment by baltpeter** [comment]
Does the solution from https://github.com/datenanfragen/website/pull/583#issuecomment-830611163 work, @mal-tee?

And if so, can we close this issue? It might be worth documenting this in the README if you've found that developing on Windows directly works reliably.

**Comment by mal-tee** [comment]
Yes, that works. Another problem on windows is the deploy.sh script, I used WSL to run it once. Besides that I see no further problem, except line endings, but that's more of an IDE/git config problem on my side. ^^

**Comment by baltpeter** [comment]
@mal-tee Do you want to work on actually fixing this or can we close this issue now that #698 is merged?

**Comment by mal-tee** [comment]
Yeah, this issue was more of a reminder to document this somewhere. :D
