### ISSUE TITLE
Discoverability of the other language versions

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#582]
> Also, please check the possibility of automatically opening the "localized" version of the website (depending upon the browser's language preferences/settings) when a user enters any of the base URL names in the browsers URL address field (no matter which "translated" site name may be specified - datarequests, datenanfragen, osobnipodaci, demandetesdonnees, pedidodedados, solicituddedatos, or any future translated name). I'm sure this will be difficult ... ;-(

That's actually something we decided against. We find automatic language redirects a lot more annoying than helpful. But I agree that the discoverability of the other language versions could be better. If you have an idea (design-wise, the implementation should actually not be too difficult) for an unobtrusive way of introducing those to users visiting the "wrong" language version, we can gladly discuss that in a new issue.

_Originally posted by @baltpeter in https://github.com/datenanfragen/website/issues/577#issuecomment-829262293_

**Comment by mal-tee** [comment]
I agree, we should improve the discoverability.

How about something like a hint in the top of the screen indicating that the page is available in a different language?

**Comment by baltpeter** [comment]
> How about something like a hint in the top of the screen indicating that the page is available in a different language?

Do you want to create a mockup or code a quick demo of what that would look like?

**Comment by mal-tee** [comment]
I am not a designer, but sure, here is my take:

![grafik](https://user-images.githubusercontent.com/45886910/116731812-7aa4e380-a9ea-11eb-82de-fe3312147326.png)

Maybe the little box should also get a different background-color or a little flag corresponding to the language. I am not sure about the flag, on the one hand it is widely known as entry point for configuring languages, on the other hand it's not really meant to represent a language in the first place.

---

I was thinking of only showing this if the current language mismatches the browsers language setting. If you dismiss it once its gone for good.

**Comment by milotype** [comment]
> I was thinking of only showing this if the current language mismatches the browsers language setting. If you dismiss it once its gone for good.

I agree ... but I'd suggest to use a "popup".
I agree ... don't use country flags.

**My suggestion**

Text for the popup:
"Change the website's language to `preferred-language` or `select` your preferred language."

- `preferred-language` should be substituted with the "translated" string for the language (Hrvatski or Deutsch, etc.) corresponding to the user's web-browser preferences. If selected, the corresponding website opens. Popup automatically closes.
- `select` should be a translatable string. When pressed or mouse over, the dropdown menu/language container should appear and the user can select one of the tranlsated language. When a language gets selected, the website should change to the translated/localized website (different domain). Popup automatically closes.

The popup could also include a button `Cancel` (already translated at Weblate), for closing the popup without changing the website/domain.

**Comment by davenewham** [comment]
Not all language tags are not BCP47 compliant - this makes the checks a little more difficult

ie. <html lang="de-de"> should really be <html lang="de-DE">

**Comment by baltpeter** [comment]
Related: #270

Seems like the `lang` attribute should [really be](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) BCP47, so we should change that anyway. Not sure why we didn't go with that in the first place, to be honest.

**Comment by davenewham** [comment]
RFC 5646 denotes that all BCP47 language tags should be treated as [case insensitive](https://www.rfc-editor.org/rfc/rfc5646.html#section-2.1.1) so not too much of an issue... However as mentioned in #270, the country code doesn't really have to exist.

However, with the preferred language - we'll have to do some funky parsing of the [Accept-Language header ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language). Don't know how willing the team is for yet another javascript package...

Maybe a naive method is just to check if "de"/"en" etc exists as a substring of the accept-language header in the first position, while as of yet the page is only available in a handful of languages.

**Comment by baltpeter** [comment]
> RFC 5646 denotes that all BCP47 language tags should be treated as case insensitive so not too much of an issue...

Ah, that's good to know. 

> However, with the preferred language - we'll have to do some funky parsing of the Accept-Language header . Don't know how willing the team is for yet another javascript package...

We are actually already using a regex to parse `navigator.language` to (badly) guess the user's country:

https://github.com/datenanfragen/website/blob/ab306ea794af818e051489860fcc805f50561bd4/src/general.js#L45-L66

We can reuse this to also get the language.
