### ISSUE TITLE
Remove prop types from production build?

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#597]
https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types

**Comment by Bhavin789** [comment]
Hello @baltpeter, if this is still open, may I give it a try? Thanks!

**Comment by baltpeter** [comment]
@Bhavin789 It has not yet been decided whether we even want to implement this (see the `discussion` label).

**Comment by Bhavin789** [comment]
Sure @baltpeter , no worries. Thanks!

**Comment by zner0L** [comment]
We moved to TypeScript since and got rid of prop-types altogether, so I will close this.
