### ISSUE TITLE
CircleCI tests sometimes fail due to timeout

### ISSUE THREAD

**Issue by davenewham** [datenanfragen/website#616]
If the server takes too long to deploy - the tests fail as it timeouts checking to see if the url is available - causing the build to be blocked on GitHub

[For example ](https://app.circleci.com/pipelines/github/datenanfragen/website/2677/workflows/80817e8f-b217-426f-8a6e-dcebe65a47c4/jobs/4363/parallel-runs/0/steps/0-103)

[Example 2](https://app.circleci.com/jobs/github/datenanfragen/website/4352?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
```
Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1

CircleCI received exit code 1
```

And even on a successful run - it gets close to not running.

```
Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
```

**Comment by baltpeter** [comment]
Good catch!

I've wondered why that happens but never looked into it as it's reasonably rare. But that makes a lot of sense.

**Comment by davenewham** [comment]
[A related issue](https://github.com/cypress-io/cypress/issues/8870). 
Seems like it's not configurable within Cypress itself.

As recommended in the issue a solution could be to use a [yet another] package, such as [wait-on](https://www.npmjs.com/package/wait-on) to detect the server is up before running the tests.

**Comment by baltpeter** [comment]
I'd say wait-on is a good workaround. Feel free to make a PR if you want, otherwise I will when I find the time.
