### ISSUE TITLE
Authors list not displayed correctly

### ISSUE THREAD

**Issue by fm** [datenanfragen/website#625]
In the all languages, the Authors list on the open source page is not displayed correctly. 
Was able to replicate in _Chrome 91.0.4472.114_, _Firefox 89.0.2_ and _Safari 14.1.1_ on macOS 11.4

<img width="1820" alt="Screen Shot 2021-07-11 at 11 23 47 PM" src="https://user-images.githubusercontent.com/3654256/125230756-0c5c8700-e29f-11eb-96f0-3f2fcb2dadb2.png">

**Comment by baltpeter** [comment]
Interesting. This previously only happened in the Netlify staging environment and I was not able to reproduce why. Curiously, the same applies to #611, so that might be related.
