### ISSUE TITLE
Input marked as related to facebook by "Facebook Container" on Firefox

### ISSUE THREAD

**Issue by lewin-7** [datenanfragen/website#633]
As I know and trust you, I am sure that none of my data is being sent to facebook. Still this add-on seems to identify this input on the generator-page as belonging to facebook. Maybe you can find out why. 

<img width="447" alt="Bildschirmfoto 2021-08-01 um 23 52 51" src="https://user-images.githubusercontent.com/84681012/127786429-7004fe34-f704-49fd-a0bd-118ca723f746.png">

**Comment by mal-tee** [comment]
Seems like this is an issue on mozilla's end: they marked every email input... :/

Seems like a fixed version is on its way: https://github.com/mozilla/contain-facebook/issues/783#issuecomment-891166030

**Comment by baltpeter** [comment]
This is now fixed: https://github.com/mozilla/contain-facebook/issues/783#issuecomment-891854434
