### ISSUE TITLE
Bring accentued letters together on company database page II

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#642]
As discussed in #245 and already fixed in #452, some characters should be grouped together on the company database. #452 solved this, but since then our database expanded and introduced new cases:

![image](https://user-images.githubusercontent.com/45886910/129492710-fa19ba6c-6579-4ea8-94b7-275e1bc84bcb.png)

The "Ε" here isn't a latin capital e (U+0045), but an uppercase epsilon (U+0395).

If you feel like we shouldn't group the uppercase e and epsilon together, we can discuss that here as well :)

To solve this issue one should:

- [ ] adjust the code introduced in #452 to also handle these new chars
- [ ] research if there are other cases where we should group characters
	- I feel like the greek alphabet and letters with a [caron](https://en.wikipedia.org/wiki/Caron) should be a great starting point

**Comment by Divyateja04** [comment]
I think I can try this out, can you assign this to me?

**Comment by Divyateja04** [comment]
I keep getting an error that partials "footer-url" not found, any idea how I fix this?
I checked code and I think partials/footer-url file is missing, can you help me out

**Comment by baltpeter** [comment]
@Divyateja04 You're probably using a Hugo version that's too old. We need v0.88.1.

I have just opened a PR to also add that to the README: #712

**Comment by Divyateja04** [comment]
Basically this happens in wsl, wsl only can update upto v0.68.3 using `sudo apt-get hugo`

You then need to install debian file, maybe add this in the windows dev section

**Comment by Divyateja04** [comment]
One more query if you don't mind, I did download node LTS only but when I run `sudo hugo server`, it says ```node_modules/.bin/postcss: 12: node not found```

Can you help me with this too, sorry for the trouble though

**Comment by baltpeter** [comment]
It's generally not a good idea to run Hugo or Yarn as root. That tends to mess up the permissions. I would recommend cloning the repo again and going through the steps without `sudo`.

Otherwise, I am not sure about the error you're getting. Some ideas:

* Have you installed Node and Yarn?
* Have you installed the Node dependencies using `yarn`?

**Comment by mal-tee** [comment]
- if you are using wsl: don't mix it with native windows programs, i.e. install all tools inside of WSL

**Comment by Divyateja04** [comment]
um does that mean I clone the repo inside wsl too, as of now my repo was cloned in the windows terminal and am running yarn dev in the windows terminal too, should I try running both from wsl only?

Node is installed in wsl, but yarn was installed outside yarn, I'll try today and get back to you

**Comment by mal-tee** [comment]
Where you clone shouldn't make much of a difference but running yarn does. Rerun  `yarn` and `yarn dev` in wsl, maybe that helps.

**Comment by Divyateja04** [comment]
yeah I'll check it today, this is my first time working on wsl so, sorry about that
Infact I'm done with improving the code, infact added all the caron letters and plan on adding others, except I can't test it rn so I had asked ,I'll check again today and get back to you

**Comment by Divyateja04** [comment]
By the way, yeah running yarn on wsl helped and maybe removing sudo too
I don't know which one helped but maybe you can add these to the docs

**Comment by Divyateja04** [comment]
I added all the caron letters, should I add other accents too to completely remove this issue for the future too?
Some accents like [acute](https://en.wikipedia.org/wiki/Acute_accent) maybe?

**Comment by Divyateja04** [comment]
By the way should I PR?

**Comment by mal-tee** [comment]
If you have a solution, sure, make a PR :+1:

**Comment by Divyateja04** [comment]
Yeah I tried to commit and it started running /scripts/merge-conflict-artifact-check.sh
I Should wait until it's done right?

**Comment by mal-tee** [comment]
Yes. Install [ripgrep](https://github.com/BurntSushi/ripgrep#installation) to make that quicker. If it takes ages anyway, you can commit with `--no-verify` to skip our hooks.

**Comment by Divyateja04** [comment]
It actually didn't take much time, can you check the PR once?
