### ISSUE TITLE
Comments: Indicate that we support some markup

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#643]
Our comments support some markup:

https://github.com/datenanfragen/website/blob/29f16ab9003ffec684cbafb4656ab3062bf9889c/src/Components/CommentsWidget.js#L98-L109

But we don't show that information on our webpages. A little hint showing our users that they can use some kind of markup should be useful.

**Comment by baltpeter** [comment]
The hint shouldn't be too prominent. The markup language used there has some quirks and is not the same as the one used in the generator (that one doesn't support nesting tags and links, most notably; the "parser" is also different).

That's mostly as the comment markup language was mostly only meant for "us" and not really for public consumption. I don't mind other people using it but it's probably only for advanced users.

For reference, see: https://github.com/datenanfragen/website/pull/297#discussion_r423922577

**Comment by duaimei** [comment]
Hi. I would like to work on this. Please assign it to me!
