### ISSUE TITLE
Right to object

### ISSUE THREAD

**Issue by Ramblurr** [datenanfragen/website#65]
I think it would be a valuable addition to the site to generate "Right to object" letters.

Often we interact with companies that for various reasons we want to have and process our data, however by default these companies also process our data for the purpose of things like direct marketing etc.

According to the GDPR we are able to object to the processing of this data, but how to do so isn't always clear.

For example, the Austrian bank Sparkasse, [has a detailed section](https://www.sparkasse.at/sgruppe/wir-ueber-uns/datenschutz-sicherheit) on how they process our data and they state that we can object, but as a lay-person I'm not sure how to effectively formulate a letter that states I object to their use of my data for particular purposes.

**Comment by baltpeter** [comment]
Thanks for the suggestion! You are right, currently objection is only handled through our erasure template. We didn't really consider cases where you *do* want to use a service but only allow them to process some data.

I'll discuss this with @zner0L.

**Comment by Ramblurr** [comment]
Given that companies provide all types of services, it would be difficult to make a template suitable for all of them.

However in most cases I think we object to the processing of our data for direct marketing and third-party processing purposes. At least of the handful of objection letters I've sent out the past month have all been against direct marketing.

I used the great existing feature to provide your own text, and then references article 21 in my text.

**Comment by baltpeter** [comment]
I agree, direct marketing is probably the most relevant. We would probably would design the template similarly to our erasure template where the generator asks you what data you want deleted. I could imagine something similar working for objections.

**Comment by baltpeter** [comment]
As a first step, I have now created a PR (datenanfragen/data#228) with a first draft of this template. After it is reviewed and merged by @zner0L, we can look at creating a blog post with sample letters and including the template in the generator.

**Comment by tstrohmeier** [comment]
I think this template could be used also in a more generic way. 

Take the sentence "ich lege hiermit Widerspruch gegen die Verarbeitung meiner personenbezogenen Daten für Direktwerbung gemäß Art. 21 Abs. 2 DSGVO ein." for example: The word `Direktwerbung` could be replaced with a list of unwanted services.

**Comment by baltpeter** [comment]
Could you expand on what you mean by "a list of unwanted services"? Art. 21(2) GDPR is (unfortunately) very specific in that it only talks about using the data for direct marketing purposes.

Or would you want to narrow that down, i.e. only object to certain types of marketing?
