### ISSUE TITLE
More accessible links in the search suggestions

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/website#650]
Instead of making the entire container a link which will be read out in full by screen readers, only use the heading. Using a clever overlay, clicking the whole container can still be preserved for visual users, like suggested in this video: https://youtu.be/qKRq-tFixWE?t=2227

This has also been discussed in #590.

**Comment by Vidushi-Gupta** [comment]
Hi, could you please let me know on which page can I change the linked containers to linked headings? I'll be happy to contribute to this. Could you please assign it to me?

**Comment by zner0L** [comment]
You can work on this if you want. We don't just want the headings to be links, we also want the the entire container to be clickable while also being semantically correct for the sake of accessibility. The youtube video I linked shows a fairly elegant solution I'd like to be implemented.

**Comment by Vidushi-Gupta** [comment]
Sure, I'll work on this. You can go ahead an assign this to me, if it requires me to be an assignee. Thank you! I look forward to contributing :)
