### ISSUE TITLE
JS error (Uncaught TypeError: Failed to fetch)

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/website#659]
**Debug information:**

```js
{
    "message": "Uncaught TypeError: Failed to fetch",
    "type": "error",
    "colno": 16861,
    "filename": "https://www.datenanfragen.de/js/commons.bundle.gen.js",
    "lineno": 17,
    "error": {
        "message": "Failed to fetch",
        "description": "fetchTemplate() failed.",
        "name": "TypeError",
        "stack": "TypeError: Failed to fetch",
        "enduser_message": "Beim Laden des Templates ist ein unbekannter Fehler passiert.",
        "context": {
            "template_url": "https://www.datenanfragen.de/templates/de/access-default.txt"
        }
    },
    "defaultPrevented": false,
    "eventPhase": 2,
    "isTrusted": true,
    "returnValue": true,
    "code_version": "1.0.0",
    "user_agent": "Mozilla/5.0 (Linux; Android 11; SM-G398FN) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.62 Mobile Safari/537.36",
    "url": {
        "ancestorOrigins": {},
        "href": "https://www.datenanfragen.de//generator#!from=wizard",
        "origin": "https://www.datenanfragen.de",
        "protocol": "https:",
        "host": "www.datenanfragen.de",
        "hostname": "www.datenanfragen.de",
        "port": "",
        "pathname": "//generator",
        "search": "",
        "hash": "#!from=wizard"
    }
}
```

**Comment by WebworkrNet** [comment]
![Screenshot_20210908-160152_Chrome](https://user-images.githubusercontent.com/43509007/132753377-44d33f16-d0fa-417c-b10a-c9978be8c8fb.jpg)

**Comment by baltpeter** [comment]
Thanks for the report! From the debug information, I'd say this was likely a temporary network hiccup (either on your or on our end). Has the problem occurred more than once? Otherwise, I'd say we can close this.

However, we should really retry failed requests. In most cases we've seen, they would have likely worked the second time around. I have opened #665 to track this.

**Comment by WebworkrNet** [comment]
> Thanks for the report! From the debug information, I'd say this was likely a temporary network hiccup (either on your or on our end). Has the problem occurred more than once? Otherwise, I'd say we can close this.

According to my memory, the error only occurred 1x.


> However, we should really retry failed requests. In most cases we've seen, they would have likely worked the second time around. I have opened #665 to track this.

Good idea!
