### ISSUE TITLE
Different spelling of the search terms

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/website#670]
Example:
https://www.datenanfragen.de/company/s-broker

If you search for `S-Broker`, the record is found, probably because of the name of the record. If I search for `Sparkassen-Broker` instead, the record is not found.

I don't know how often this happens. 
Can this be intercepted?

**Comment by baltpeter** [comment]
This behaviour is given by the search engine we use, Typesense. It's actually the same problem as reported in #495, so I will close this issue.

This will likely soon be fixed. The awesome Typesense people have recently published a new release candidate that fixes this problem, see their issue typesense/typesense#122. If you're interested, I have also posted a detailed comment evaluating these changes for our project in their issue and they have already fixed the main problem I have found: https://github.com/typesense/typesense/issues/122#issuecomment-907489433
