### ISSUE TITLE
Company database: Alphanumeric sorting of the "runs" entries

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/website#672]
Particularly long lists become confusing to the human eye. An alphanumeric sorting would remedy the situation.

**Comment by baltpeter** [comment]
Hm, not sure about this. We often have "runs" entries that first list other services the company runs (which are usually interesting to the user) and then list different companies/legal entities they are responsible for (which usually aren't that interesting to the user and most included to clarify that the request also covers them). One example for that: https://www.datarequests.org/company/match-group/

If we sort them, this separation would get lost.

**Comment by WebworkrNet** [comment]
Ok, I understand. However, it is obvious to users that such a sorting exists. Only the people involved know the principle.

**Comment by baltpeter** [comment]
When talking about “users”, do you mean those who edit the company database or those who just use it? I don't think it's important for the latter to know this. The important entries are at the beginning of the list for them.
