### ISSUE TITLE
Query generator: Positioning of the submit buttons

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/website#673]
In my opinion, the buttons for sending emails and new enquiries are positioned in an unfortunate way. The user works through the form line by line from top to bottom. Consequently, for the sake of user-friendliness, there should also be submit buttons at the bottom of the form.

If there are compelling reasons to place the buttons at the top of the page, then I would like to suggest that additional buttons be placed at the bottom.

**Comment by nilesh-sengupta** [comment]
Hello , I would like to work on it . Can you  just inform me the location where the code for the mentioned buttons in the repository ?

**Comment by mal-tee** [comment]
I think it's a bit too early to implement this, as this still needs to be discussed in the first place. Maybe @baltpeter or @zner0L could give us some insight on their reasoning back then.

**Comment by mal-tee** [comment]
Sorry, we are not really interested in an implementation right now.

**Comment by baltpeter** [comment]
This new wizard-style interface has now been released for half a year, so I think this can be closed.
