### ISSUE TITLE
Österreichischer Rundfunk (ORF) not found

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/website#677]
Don't know if this bug falls under #495 like #670. The record `Österreichischer Rundfunk (ORF)` is not found under `Österreichischer`, `Rundfunk` or `ORF`.

**Comment by mal-tee** [comment]
All three work for me. Did you set the right Country on datenanfragen.de? The record will only show up for "all" and "Austria". As its relevant countries is only set to "at".

https://github.com/datenanfragen/data/blob/7c20b1dfc2c75d92d2a10ec75295d131eaf6be96/companies/orf.json#L4

**Comment by WebworkrNet** [comment]
Thank you, ok right. I had not thought of the selection by country in this context.
