### ISSUE TITLE
Record failed production tests in Cypress

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#679]
We have a test configured in Circle CI that automatically tests our production site on a schedule:

https://github.com/datenanfragen/website/blob/f9cc1f0c88c1f1768e3b418efcabb0aed80cf807/.circleci/config.yml#L97-L111

Unlike our "regular" tests, this doesn't record the runs to the Cypress dashboard. We should record failed production tests as well to ease debugging them. 

This should be as simple as adding `--record` to `yarn cypress run` if the `CYPRESS_RECORD_KEY` env var is set and the run failed.

**Comment by imrishabh18** [comment]
I would like to take this up

**Comment by mal-tee** [comment]
Happy hacking, I will assign you.

**Comment by AnirbanBall** [comment]
I would like to work on this

**Comment by mal-tee** [comment]
Sorry, @imrishabh18 Is already working on this.
