### ISSUE TITLE
Support non-EU countries Serbia and Turkey

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/website#682]
The country "Serbia" is not available for selection. Admittedly, it is not a member of the EU (yet), but the current list of countries also includes non-members such as Norway, Switzerland or the United Kingdom.

**Comment by baltpeter** [comment]
This is intentional. We are only allowing countries where the GDPR applies as everything else is out-of-scope for our project.

See https://github.com/datenanfragen/data/issues/764 and https://github.com/datenanfragen/data/pull/766.
