### ISSUE TITLE
Exclude `nsfw` companies from "related companies"

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#711]
In datenanfragen/data#1368, we added a new `nsfw` field to our company record schema. In our governing association's general assembly on September 15, 2021, we adopted a resolution that says that NSFW companies need to be excluded from the "related companies" list.

Here's the relevant code:

https://github.com/datenanfragen/website/blob/a24f55bae16f33240af7bc0ce3715806c81c9f81/layouts/partials/related-companies.html

**Comment by Torfab** [comment]
may i work on it?

**Comment by baltpeter** [comment]
@Torfab Sure, I have assigned you.
