### ISSUE TITLE
Dockerize project to make it more accessible to newcomers

### ISSUE THREAD

**Issue by duaimei** [datenanfragen/website#721]
Create a docker and docker-compose file so that people don't necessarily have to have Hugo and Yarn on their personal machines. Everyone's development environment is a little bit different, and this will help with basic errors.

For example:
I'm on a mac and `hugo server` failed, but `hugo server --watch=false` worked.

**Comment by mal-tee** [comment]
I think that specific problem is documented in the README, but sure. I think its a idea worth giving a shot, but only for developing purposes. 

Shouldn't be too hard to implement for sb. with Docker knowledge. But I am not sure if we/@baltpeter want to maintain Docker-config stuff as well. :thinking:

**Comment by baltpeter** [comment]
Thanks for the suggestion!

As @mal-tee said, this would only be for dev purposes (as the project really isn't meant to be deployed by anyone other than us). Personally, I don't really see the need for that. Between the instructions and tips in the README, I think it shouldn't be too hard to get up and running for dev. And with #701, this will get even easier.

> But I am not sure if we/@baltpeter want to maintain Docker-config stuff as well.

We could consider it if someone steps up to maintain that in the future. I will not be doing that.

**Comment by joremysh** [comment]
maybe I could help add a dockerfile to the project

**Comment by zner0L** [comment]
I actually don't like this at all. Hugo and yarn are easy to use and build consistently across platforms. Docker just adds unnecessary overhead and adding a Dockerfile suggests that using Docker is needed for development or deployment. We even already provide containerization information for the CI (and netlify kinda). IMO, there is no need for docker if everybody already has a perfectly working unix shell in their OS.
