### ISSUE TITLE
Hide fixed fields with same value as the generator in the dropdown

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#735]
On our [“My saved data” page](https://www.datarequests.org/id-data-controls/), you can enter your details for them to be prefilled in the generator. You can also add your own fields which is useful for example if you have multiple email addresses.

In the generator, we have a dropdown where you can manually add them to the identification data (we call them "fixed fields"):

https://user-images.githubusercontent.com/4048809/136290810-21ce7184-86d6-4a61-a7d1-7e59289e5960.mp4

But fields that are already present in the ID data are still displayed even though clicking them again won't do anything (or add them a second time, which doesn't make sense either):

https://user-images.githubusercontent.com/4048809/136290977-81f97abb-dd76-4c09-950a-c944783ff872.mp4

Instead, we should hide fields that are already present in the ID data (and have the same value!).

**Comment by marlonemmerich** [comment]
Hello, friend! I created a PR (https://github.com/datenanfragen/website/pull/788)
Please, check if now makes sense for you: now, if the new field have the same type and value of anyone that was before inserted we don't insert.

If i did any mistakes or if you need more help, just tell me!

Have a nice day!

**Comment by Jaagrav** [comment]
Oh crap, I thought this issue was going to go stale cause you were assigned 10 days ago 😅 
Anyway in my PR I hide the fixed field like requested in the issue, you can close my PR if you want to.

**Comment by marlonemmerich** [comment]
Oh god, sorry =\
I had some problems, I just had time to do this yesterday
But your'e right: the issue told to hide the fields and I don't did that, you put more energy on this and did a great job!
I really understand if we use your PR instead of mine!

**Comment by marlonemmerich** [comment]
I have a idea! You did a confirmation with a alert. What you think if we use this modal confirmation? Like this:
![zlomklo](https://user-images.githubusercontent.com/52637919/137632754-e5d675f0-c168-4ce5-93ca-ac6442d53f26.png)

Maybe I can do this! In this case, you and me get a hacktoberfest PR ;)
