### ISSUE TITLE
Running both starting scripts in a single terminal 

### ISSUE THREAD

**Issue by Rafajrg21** [datenanfragen/website#738]
When I forked the project and started my developing process I thought about how it would be easier to run both starting commands (**yarn dev** and **hugo server**) in a single terminal. 

My proposal is to add the [concurrently](https://www.npmjs.com/package/concurrently) package to the Dev dependencies and use it from a single **start** script. Personally I think that's a better developer experience than having two terminal tabs/windows open.

**Comment by baltpeter** [comment]
Thanks for the suggestion. So far, we haven't done that as both Hugo and Webpack produce a fair amount of (sometimes relevant) terminal output and this approach would mix them, making it harder to read.

And with the changes in #701, this won't be necessary anymore anyway, as we are then building the JS through Hugo as well.
