### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#773]
Thanks to @skvrnami we are almost ready to prepare the website and deploy a new language! 🥳 

There are still a few things TODO, I'll probably miss some, but this issue can be used to track our progress.

- [x] Domain name
	- @skvrnami Do you have an idea for a nice domain name? It should be a translation of "datarequests" or something similar. 
- [ ] After the translation part is done, we have our own list for "code"-stuff at https://github.com/datenanfragen/website/blob/master/src/i18n/README.md
	- We'll do that, you don't have to. :D  
- [x] language maintaining
	- @skvrnami Would you be up to maintaining the translated website in the future? That means checking incoming translations from PRs or updating templates and strings if we make changes. Shouldn't be too much work, but it would be amazing, if we have a contact person for the translated languages we can not speak ourselves. :D

**Comment by skvrnami** [comment]
Sorry for the delay, after some thinking I think that "zadamudaje" is the best option. ("Žádám údaje" means "I am requesting the data").

**Comment by zner0L** [comment]
I think I like the first one better. We try to use names which are not only about accessing data but also other requests concerning personal data e.g. erasure requests.

**Comment by mal-tee** [comment]
How should we proceed here? Seems like the only hold-up is the name?

**Comment by mal-tee** [comment]
@baltpeter @zner0L 

I'm with every name. :)

**Comment by milotype** [comment]
I don't speek Czech. Maybe it helps to check the issue #566 about the Croatian domain name ...

**Comment by mal-tee** [comment]
> I think I like the first one better. We try to use names which are not only about accessing data but also other requests concerning personal data e.g. erasure requests.

We are very sorry for the delay. But we want to launch this soon!

@skvrnami do you have another suggestion or idea based on @zner0L's comment? We want to keep the "general request" meaning in the name instead of only covering data access requests. Seems like "zadamudaje" only covers the latter.

**Comment by skvrnami** [comment]
@mal-tee yeah, it does cover only the latter. zadostioudaje is more general, although it is a bit convoluted (but ok, I guess).
