### ISSUE TITLE
noindex the Netlify builds

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#81]
The branch builds are also indexed by Google. Probably not a good idea.

**Comment by baltpeter** [comment]
We want to block *all* pages for the staging environment and *no* pages for the production environment.

**Comment by sakkshm** [comment]
Can you please make a list of all of the URLs and directories! It would really help.

**Comment by baltpeter** [comment]
Such a list doesn't exist and it cannot exist because we constantly add new URLs. It is also not necessary for this issue.

All that needs to be done is to add the noindex meta tag depending on whether we are in the staging environment to the Hugo `baseof.html` template.
