### ISSUE TITLE
Upgrade the Issue Template to use GitHub Issue forms

### ISSUE THREAD

**Issue by Rutam21** [datenanfragen/website#811]
## Introduction
GitHub has recently rolled out a public beta for their issue forms feature. This would allow us to create interactive issue templates and validate them.

Datenanfragen-Website currently doesn't use any issue template format. The task is to create GitHub issue forms for this repository. 

## Tasks summary:
 - [ ] Fork & clone this repository
 - [ ] Prepare bug report issue form in .github/ISSUE_TEMPLATE/bug.yaml
 - [ ] Prepare documentation issue form in .github/ISSUE_TEMPLATE/documentation.yaml
 - [ ] Prepare feature request issue form in .github/ISSUE_TEMPLATE/feature.yaml
 - [ ] Push changes to master and test issue forms on your fork
 - [ ] Submit pull request

**Comment by Rutam21** [comment]
@baltpeter Please take a look at this issue and let me know if it looks good to you. Please add appropriate `hacktoberfest` labels as well.

**Comment by baltpeter** [comment]
Sorry but that is not something that we are interested in.
