### ISSUE TITLE
Make dropdown into a component

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#83]
Also add `aria-expanded` to the content `<div>`.

**Comment by thebhushanmhatre** [comment]
I will work on this

**Comment by baltpeter** [comment]
Thank you!

**Comment by thebhushanmhatre** [comment]
Hi @baltpeter, Can you provide with some more information on the task, I mistook this as a simple html dropdown addition for my first PR. And also can you also mention which files need to be changed.
Thanks.

**Comment by baltpeter** [comment]
Hi @thebhushanmhatre, we already have dropdowns in several places (like [here](https://github.com/datenanfragen/website/blob/master/layouts/_default/baseof.html#L56)). We want to make them more reusable by making them into a React component.

Let me know if you need any more details.

**Comment by thebhushanmhatre** [comment]
I am not familiar with technological stack and there were many things I didn't understand.
So instead of further spending time on this, Its better if somebody else continues on this.
Thanks.
