### ISSUE TITLE
Restructure content dir

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#85]
We could structure our content more sensibly.

Suggestions:

* Use folders for i18n instead of filenames.
* Include images for a blog post in the corresponding content folder instead of in the `static` dir.

**Comment by nSedrickm** [comment]
Hi. How can I help?

**Comment by baltpeter** [comment]
We want to restructure our content folders for Hugo. See these two help pages for more details:

* https://gohugo.io/content-management/organization/
* https://gohugo.io/content-management/multilingual/#translation-by-content-directory

**Comment by nSedrickm** [comment]
Ok.I will.

**Comment by nSedrickm** [comment]
Hi. I have read through both pages. How do you want the content restructured? How do I achieve this?

**Comment by baltpeter** [comment]
We are looking to implement the two suggestions mentioned in the first post of this issue. The pages I linked explain how to do this.
