### ISSUE TITLE
Don't add empty fields to the letter

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#87]
If a user leaves an input empty, that field should not be added to the generated letter.

**Comment by hendaoui** [comment]
I'm working on it ;)

**Comment by ggangix** [comment]
I would like to work on it.

**Comment by baltpeter** [comment]
Sure, thank you! Let me know if you have any questions.

**Comment by ggangix** [comment]
Hi, looks like I need some orientation to start the development version, after run yarn dev, I can't find in witch port the server is? I thought that was something like 8080. Or have I to do something more? 

Sorry for the question and thanks.

**Comment by baltpeter** [comment]
No worries, we absolutely do need to work on our docs for that.

In addition to `yarn dev`, you also need to run `hugo server --disableFastRender` to actually build the site and serve it. Also make sure you've executed [`deploy.sh`](https://github.com/datenanfragen/website#development) before to make sure you have a local copy of the company database.

**Comment by baltpeter** [comment]
Hi! Just a quick note: We are now officially participating in the Hacktoberfest. Anyone who submits a PR to one of our repositories can get a free sticker set from us in addition to the regular swag by DigitalOcean.

Here's our blog post on the subject: https://www.datarequests.org/blog/hacktoberfest-2019/

**Comment by ggangix** [comment]
Hey @baltpeter thanks for your help to run the server, now I am working in the issue and I would like to know witch should be the expected result, currently I remove all the empty fields from the letter, but we still have this line:

"Zur Identifikation einer Person habe ich folgende Daten beigefügt:" 

Should we remove this line if the user doesn't fill any field?

Thanks again.

**Comment by baltpeter** [comment]
That's a great point, I hadn't even considered that!

Removing that line would probably be the best course of action, yes. I think the easiest way would be adding a flag to the template like we are already doing for data portability. You would then only have to set a new flag attribute in the `Request` object and make sure it gets passed along [here](https://github.com/datenanfragen/website/blob/master/src/Utility/RequestLetter.js#L141).

**Comment by sibis** [comment]
@baltpeter Debugging this code locally on my dev machine. Can you please elaborate on this issue. Please throw some more lights on the areas like `steps to reproduce` which will help us to test the current scenario. Thanks

**Comment by baltpeter** [comment]
Hi @sibis, this issue is already being worked on by @ggangix. I'll gladly provide more details for any other issues you want to work on.

**Comment by baltpeter** [comment]
Have a look at #88 for example. That one is quite similar. I can post more details on that if you want.
