### ISSUE TITLE
Only prompt for removal confirmation when a dynamic input actually contains user-entered data

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#88]

**Comment by sibis** [comment]
@baltpeter Sure. please elaborate more on this issue. I would like to work on this :)

**Comment by baltpeter** [comment]
**Steps to reproduce:**

![website-gh-88](https://user-images.githubusercontent.com/4048809/66229524-8971ca00-e6d1-11e9-8235-8530370cd401.gif)

1. Open the generator.
2. Enter some value into one of the "My data" inputs.
3. Try to delete the input with the data entered. You are asked for confirmation. This is intentional and wanted behavior.
3. Try to delete an input *without* data in it. You are still asked for confirmation. This is not necessary and should be removed.

Hope that clears it up. :)

**Comment by sibis** [comment]
Great. :) Got it @baltpeter.

**Comment by baltpeter** [comment]
Done in #101.
