### ISSUE TITLE
Blog post: Essential browser extensions for more privacy

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#89]
This should include extensions like HTTPS Everywhere, Privacy Badger etc.

We should also strongly recommend using Firefox.

The post can be in English or German.

**Comment by abhisheknaiidu** [comment]
I would like to work on it!

**Comment by baltpeter** [comment]
Sure, thank you! If you need any help, let me know.

**Comment by abhisheknaiidu** [comment]
So should i write and post an article related to it here only ?

**Comment by baltpeter** [comment]
Not quite sure if I understand your question, to be honest. Our blog posts are saved as Markdown files in [this directory](https://github.com/datenanfragen/website/tree/master/content/blog). Feel free to have a look at the existing ones to get an idea what they look like.

**Comment by nishantwrp** [comment]
@baltpeter I would like to work on it

**Comment by nishantwrp** [comment]
@baltpeter I've made a pull request adding this blog.
