### ISSUE TITLE
Blog post(s): Automatic data export features

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#90]
Many services now offer automatic data download features. We should have blogs posts describing how to use them. These posts could maybe also include screencasts or at least screenshots of the process.

A list of services I can think of (although there are more of them):

* Twitter
* Facebook
* Apple
* Google
* Duolingo
* Spotify

These posts can be in English or German.

**Comment by abhisheknaiidu** [comment]
I would like to work on it! but could u explain a little bit more regarding this?

**Comment by baltpeter** [comment]
Not sure if you've taken a look at the [website](https://www.datarequests.org) yet but our goal is to make it as easy as possible for users to exercise their GDPR rights. For some services, like [Google](https://support.google.com/accounts/answer/3024190?hl=en) and [Facebook](https://www.facebook.com/help/1701730696756992?helpref=hc_global_nav) for example, you don't even need to send an access request because they offer tools to export and download your data.

The idea is to pick one or more of these services and write a post on how to use that feature for that particular service. These post should also include screenshots, showing each step of the way. 
Ideally, they would also describe the data included in the export and how to use that.

Here is a similar post on a different site: https://www.askdavetaylor.com/export-data-facebook/

**Comment by baltpeter** [comment]
Hi everyone! Just a quick note: We are now officially participating in the Hacktoberfest. Anyone who submits a PR to one of our repositories can get a free sticker set from us in addition to the regular swag by DigitalOcean.

Here's our blog post on the subject: https://www.datarequests.org/blog/hacktoberfest-2019/
