### ISSUE TITLE
Automatically crop the signature

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#91]
It would be great if we could crop the signature.

Whenever I tested the signature input, I found it quite hard to judge how much space was needed for my signature and often ended up with quite large margins (especially at the top and bottom) which look fairly ugly in the PDF.

**Comment by Snaked06** [comment]
We can use Imagemagick To succesfully do this for example https://stackoverflow.com/questions/50187924/auto-crop-textsignature-from-image-and-change-background-color-using-imagemagi

**Comment by baltpeter** [comment]
Thanks for the suggestion, I don't think ImageMagick works on the client-side, though. Besides, I would like to try and avoid pulling in that big of a dependency, the generator is already quite heavy.

This should be possible in plain JS using the canvas APIs.

**Comment by merelj** [comment]
that sounds like a cool feature, I'd like to try :)

**Comment by baltpeter** [comment]
Sure, thank you!

**Comment by merelj** [comment]
@baltpeter 
opened [this pr](https://github.com/datenanfragen/website/pull/135), but still need some help with it :(
