### ISSUE TITLE
Indicate when we consider a request done

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#92]
When working with the wizard, it is sometimes easy to forget if you have sent the request that is currently open already (especially when pausing for a while).

Since we already have a point at which we consider a request 'done', we should simply indicate that to the user (by changing the color of the button or something similar).

**Comment by peterjgrainger** [comment]
can I take this one?

**Comment by baltpeter** [comment]
Sure, thanks!

**Comment by peterjgrainger** [comment]
<img width="279" alt="image" src="https://user-images.githubusercontent.com/1332395/66820739-28e85580-ef39-11e9-846c-144fd6a0048b.png">

Does that look OK?

**Comment by baltpeter** [comment]
Also tagging @zner0L for feedback.

Not sure from the screenshot but are you using a color from our [palette](https://www.datarequests.org/design)?

**Comment by peterjgrainger** [comment]
Before 

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/1332395/66821220-fc810900-ef39-11e9-8d1b-e2853bb147f2.png">

After 

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/1332395/66821187-ea9f6600-ef39-11e9-91b1-fa30ee9dd5d9.png">

**Comment by peterjgrainger** [comment]
@baltpeter I didn't know about your palette! I'll have to choose something from there. I was also wondering if this is a good way to indicate the request has been completed?

**Comment by peterjgrainger** [comment]
I used the `css`

```
        background-color: color('green', 800); 
        color: color('gray', 200) !important;
        border: 2px solid color('green', 800);
```

Which looks like the correct value from the palette 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/1332395/66821712-c8f2ae80-ef3a-11e9-9b54-c283e81390cb.png">

**Comment by baltpeter** [comment]
No worries, the colors are available through the `color` SCSS function (e.g, `color('gray', 800)`). One of the teals would probably work best.

I am not sure whether this is a good indicator. It might not be clear to the user. Some other options I could imagine working:

* a checkmark (either replacing the current icon or in addition to that)
* maybe also simply removing the primary button treatment and making it into a secondary button?

What do you think, @zner0L?

**Comment by peterjgrainger** [comment]
This is what it looks like 

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/1332395/66822560-613d6300-ef3c-11e9-898e-5a2e38ec0780.png">


Not sure about the checkmark though. Let me know which one your like https://iconmonstr.com/?s=check

**Comment by baltpeter** [comment]
> Maybe I can change the wording? Though that might confusing because they might want to send the email again...

Good point. 

What about changing it to 'Send email again' though? That should make it clear that the request has been sent already while also making it easy to actually send it again if the user wants to.

**Comment by peterjgrainger** [comment]
Maybe we can have a different icon per type of request e.g. for email we could have ![paper plane](https://cdns.iconmonstr.com/wp-content/assets/preview/2013/240/iconmonstr-paper-plane-7.png)

**Comment by zner0L** [comment]
> What about changing it to 'Send email again' though? That should make it clear that the request has been sent already while also making it easy to actually send it again if the user wants to.

I'd like the wording to also be changed. I think the symbol alone is not strong enough of an indicator and it is also not accessible. It would be great if you could incorporate that into you PR, @peterjgrainger.

And just another thought: What about the PDFs? I think we should do the same thing there. What do you think @baltpeter?

**Comment by zner0L** [comment]
Whoops. Didn't mean to close this.

**Comment by baltpeter** [comment]
Yep, the same treatment should also be applied to the PDFs.

If we change the text, I am also not opposed to changing the icon to a transport medium-specific "sent" version (like the paper plane @peterjgrainger suggested and maybe a mailbox for letters?). Most users will probably not notice that but I think it makes for a nice easteregg.

**Comment by peterjgrainger** [comment]
So in summary:
- Change the wording
  - Send email -> send email again
  - Download PDF -> Download PDF again
- Change button style to be a secondary button
- Change icon
 - email -> paper plane
 - PDF -> slightly different icon? (see below)

PDF before download

![image](https://user-images.githubusercontent.com/1332395/67001224-2456a500-f0d1-11e9-9f2c-9ca2ea0f1f6a.png)

PDF after download 👇 

![iconmonstr-download-3](https://user-images.githubusercontent.com/1332395/67001179-0ee17b00-f0d1-11e9-8f21-a8257afd9606.png)

**Comment by zner0L** [comment]
That sounds correct. I like @baltpeter's idea of a mailbox icon for the PDF more, though.

**Comment by peterjgrainger** [comment]
There isn't anything on https://iconmonstr.com where all the other icons are from

What about 👇 ?

![letter](https://cdns.iconmonstr.com/wp-content/assets/preview/2017/240/iconmonstr-email-15.png)

**Comment by zner0L** [comment]
We actually like the idea of this icon to be a little unusual. Maybe this delivery truck? https://iconmonstr.com/delivery-5-svg/

**Comment by peterjgrainger** [comment]
All the changes are in https://github.com/datenanfragen/website/pull/133

Have a look and tell me what you think?

**Comment by peterjgrainger** [comment]
I'm having some issues with the new icon `svg` images. It might be breaking the build I'm not sure. Have you seen this error before?

```
    ERROR in ./node_modules/iconfont-webpack-plugin/placeholder.svg (./node_modules/iconfont-webpack-plugin/lib/loader.js?{"svgs":["res/icons/letter.svg","res/icons/pencil.svg","res/icons/trash.svg","res/icons/arrow-down.svg","res/icons/arrow-up.svg","res/icons/arrow-right.svg","res/icons/arrow-left.svg","res/icons/menu.svg","res/icons/fill.svg","res/icons/print.svg","res/icons/download.svg","res/icons/email.svg","res/icons/paper-plane.svg","res/icons/delivery-truck.svg","res/icons/i18n.svg","res/icons/close.svg","res/icons/json-document.svg","res/icons/rss.svg"],"name":"H3605f","enforcedSvgHeight":1000}!./node_modules/iconfont-webpack-plugin/placeholder.svg)
    Module build failed (from ./node_modules/iconfont-webpack-plugin/lib/loader.js):
    Error: Error: Got an error parsing the glyph "i13": Expected a flag, got "01" at index "16". - Tried to compile: [
      "res/icons/letter.svg",
      "res/icons/pencil.svg",
      "res/icons/trash.svg",
      "res/icons/arrow-down.svg",
      "res/icons/arrow-up.svg",
      "res/icons/arrow-right.svg",
      "res/icons/arrow-left.svg",
      "res/icons/menu.svg",
      "res/icons/fill.svg",
      "res/icons/print.svg",
      "res/icons/download.svg",
      "res/icons/email.svg",
      "res/icons/paper-plane.svg",
      "res/icons/delivery-truck.svg",
      "res/icons/i18n.svg",
      "res/icons/close.svg",
      "res/icons/json-document.svg",
      "res/icons/rss.svg"
    ]
```

**Comment by zner0L** [comment]
Oh, yes. You are right, the problem seems to be the `imagemin-lint-staged` package. I am investigating further.
