### ISSUE TITLE
Translate GDPR cheat sheet blog post from German to English

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#93]
We have a [GDPR cheat sheet blog post](https://www.datenanfragen.de/blog/dsgvo-glossar/) ([this file](https://github.com/datenanfragen/website/blob/master/content/blog/gdpr-cheat-sheet.de.md)) that is essentially just a short explanation of important GDPR terms and topics.

That blog post is currently only available in German. We should translate it to English.

**Comment by drd-2rcl** [comment]
Hi, i would like to get this issue

**Comment by baltpeter** [comment]
Sure, thank you!

**Comment by baltpeter** [comment]
Hi! Just a quick note: We are now officially participating in the Hacktoberfest. Anyone who submits a PR to one of our repositories can get a free sticker set from us in addition to the regular swag by DigitalOcean.

Here's our blog post on the subject: https://www.datarequests.org/blog/hacktoberfest-2019/

**Comment by MIP2000** [comment]
Hello, i translated the post! Check if everything is alright. Thanks a lot.

**Comment by xeluna** [comment]
I think this issue can be closed since the PR has been merged. :)

**Comment by baltpeter** [comment]
It certainly can. I am too used to that happening automatically from the commit messages. :D Unfortunately, we can't do that right now as we are running GitHub and a private GitLab instance in parallel with different issue numbering systems… Oh well.
