### ISSUE TITLE
Decide how to integrate app into the website

### ISSUE THREAD

**Issue by zner0L** [datenanfragen/website#935]
The app, or, as I started calling it, the "tool", i.e. the new generator interface needs to go somewhere on the webpage. On `new_ux` it currently just replaces the generator of which @baltpeter always said that we want to keep it. So if we keep it like it is, which would keep a lot of links intact if we support the old linking scheme, we need to find a place for the legacy generator. Maybe just datenfragen.de/legacy?

**Comment by baltpeter** [comment]
I already placed the old generator at /g, which is a bit silly but I also kind of like it.
