### ISSUE TITLE
Request types have inconsistent capitalisation + delete icon moves

### ISSUE THREAD

**Issue by davenewham** [datenanfragen/website#949]
![image](https://user-images.githubusercontent.com/15076177/197161308-38f2a0fc-ea78-4dcf-9043-e9c04094a59b.png)

**Comment by baltpeter** [comment]
We're actually working on a major update on the `new_ux` branch that will completely replace the existing "My requests" UI. It's mostly done, we're just working on a few finishing touches before we merge. :)

You can see a deploy preview at https://deploy-preview-921--datenanfragen.netlify.app/.
