### ISSUE TITLE
Make the privacy controls use our custom checkbox styles

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#96]
The checkboxes for the privacy controls (`/privacy-controls`) are currently using the default checkbox styles. We have our own checkbox styles, though. These should also be used here.

Essentially, this should boil down to adding the `form-element` class and maybe some minor layout tweaking to make sure things align nicely.

---

This is what they currently look like:

![image](https://user-images.githubusercontent.com/4048809/66233977-1457c200-e6dc-11e9-973a-c5f91bb219d5.png)

This is what they should look like:

![image](https://user-images.githubusercontent.com/4048809/66233997-22a5de00-e6dc-11e9-85f0-428e28d42d45.png)

(This is part of the "My saved data" page (`/id-data-controls`), relevant code is [here](https://github.com/datenanfragen/website/blob/master/src/id-data-controls.js#L54)).

**Comment by ggangix** [comment]
I will try to solve this issue.
