### ISSUE TITLE
Error handler: Filter out 1Password errors in Safari

### ISSUE THREAD

**Issue by fm** [datenanfragen/website#960]
Website is showing an error pop-up on every page load. Only seems to trigger in Safari (tested using Version 16.1 (18614.2.9.1.12)). Does not trigger in Chrome or Firefox. WebKit-specific issue?

<img width="1885" alt="Screenshot 2022-11-27 at 3 01 41 PM" src="https://user-images.githubusercontent.com/3654256/204139298-7374c9bf-8905-426c-931b-e132f13d8e6e.png">
<img width="1885" alt="Screenshot 2022-11-27 at 3 01 45 PM" src="https://user-images.githubusercontent.com/3654256/204139294-b4045226-c235-4d5e-b4fc-21c919b78a07.png">

**Debug information:**

```js
{
    "type": "unhandledrejection",
    "error": {
        "message": "Error response received for message <get-frame-manager-configuration>",
        "name": "Error",
        "stack": "@webkit-masked-url://hidden/:17:189527"
    },
    "defaultPrevented": false,
    "eventPhase": 2,
    "isTrusted": false,
    "returnValue": true,
    "code_version": "1.0.0",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15",
    "url": {
        "href": "https://www.datarequests.org/",
        "protocol": "https:",
        "host": "www.datarequests.org",
        "hostname": "www.datarequests.org",
        "port": "",
        "pathname": "/",
        "search": "",
        "hash": "",
        "origin": "https://www.datarequests.org",
        "ancestorOrigins": {}
    }
}
```

**Comment by zner0L** [comment]
This might actually not be an issue with our website, but [1Password](https://1password.community/discussion/125208/safari-extension-often-loses-connection-to-1password). Do you use the extension in Safari and does the issue still occur if you disable it?

**Comment by baltpeter** [comment]
Thanks! I've tried to reproduce this in Safari 15.3 and GNOME Web 42.4 (WebKitGTK 2.38.2) and didn't encounter an error, so maybe @zner0L is right.

**Comment by fm** [comment]
@zner0L Is right... it was my good friend 1P. Interestingly, disabling and re-enabling the extension fixed it. _(It worked when disabled, and kept working once enabled again)._ 

 I shall now close this issue.

**Comment by baltpeter** [comment]
It might be interesting to test whether that was a problem with your specific setup or whether it always occurs with the 1PW extension in Safari. In the latter case, we might want to filter that out in our error handler.

**Comment by fm** [comment]
The thread makes it sound like it's a known issue. I also have a friend at 1P I can ping...

**Comment by baltpeter** [comment]
Not sure whether this is also 1PW but certainly a similar error report we just received via email:

```
error.message := null is not an object (evaluating 'document.getElementById("one-sec").remove')
error.name := TypeError
error.stack := hideOneSecOverlay@webkit-masked-url://hidden/:146:39
handleResponse@webkit-masked-url://hidden/:193:26
promiseReactionJob@[native code]
user_agent := Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1
```

My guess is that we also want to filter out `webkit-masked-url://`.

**Comment by mal-tee** [comment]
https://bugs.webkit.org/show_bug.cgi?id=246010 seems like it

**Comment by zner0L** [comment]
I suspect this was related to a different extension in mobile Safari, related to the [one-sec App](https://one-sec.app/). But the stack certainly looks similar. I think we could filter for `@webkit-masked-url://hidden/`.
