### ISSUE TITLE
Investigate which adblock-list/browser extension removes mastodon icon

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#967]
Some users reported that the mastodon icon in the footer is missing, this is probably due to some browser extension. Let's find out which and why. :)

**Comment by baltpeter** [comment]
A user has identified "Fanboy's Annoyance" and "Fanboy's Social".

**Comment by mal-tee** [comment]
Annoyance seems to include Social.

> Fanboy Annoyances List
> 
> In page Pop-Ups and other annoyances; thereby substantially decreasing web page loading times and uncluttering them (includes Fanboy-Social List.)

https://fanboy.co.nz/

**Comment by mal-tee** [comment]
In my Firefox, the list doesn't remove the icon on datenanfragen.de but on datarequests.org.

The match in question is with the filter `##[title^="Follow us on "]`. So I'd say the list works as intended. We can consider changing the string to circumvent the list, but that seems dirty.

**Comment by baltpeter** [comment]
I agree. This is clearly not a mistake in the list but working as intended. If people want to block social links, that's their choice.

I'd say we can close this issue and use it as a reference to potential future reports.

**Comment by mal-tee** [comment]
Jup. 

https://github.com/easylist/easylist/blob/33970aed10f5beb920745cb1ffbed37a3fa26954/fanboy-addon/fanboy_social_general_hide.txt#L13234
