### ISSUE TITLE
Clicking the description of a privacy control should toggle the checkbox

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#97]
On the privacy controls page (`/privacy-controls`), clicking the description of a control should also the checkbox.

The relevant code is [here](https://github.com/datenanfragen/website/blob/master/src/privacy-controls.js#L70).

**Comment by Snaked06** [comment]
I will like to this issue

**Comment by baltpeter** [comment]
Sure. Have fun and thanks!

**Comment by Snaked06** [comment]
Done

**Comment by baltpeter** [comment]
Fixed in #99. Thanks!
