### ISSUE TITLE
Allow deleting individual saved requests

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#98]
On the "My requests" page (`/my-requests`), there is currently only the option of deleting all saved requests.

There should be a delete button next to each request (in a new column), allowing the user to delete individual requests.  
We already have a delete button design (in the wizard, for example). This should be used here, as well.

![image](https://user-images.githubusercontent.com/4048809/66234802-263a6480-e6de-11e9-96dc-1c334be28d21.png)

In addition, the user should be able to delete multiple requests at once (the selected ones), just like they can export the selected requests.

**Comment by MeisterRed** [comment]
Hi, I would like to work on this.

**Comment by baltpeter** [comment]
Great, thank you!

**Comment by MeisterRed** [comment]
Hey. I'm having some trouble with completing the issue due to it be a bit harder than expected. I'm not super experienced with react so I think its best someone else take the issue from here. My apologies

**Comment by baltpeter** [comment]
No worries, thanks for trying!

**Comment by xeluna** [comment]
Hello, I'd like to work on this. May I ask if there's a deletion message text that should be shown?

**Comment by baltpeter** [comment]
@xeluna Thank you!

What do you mean by that? The specific text you use is not that important, we'll have to translate it anyway, so we can make changes then if necessary.

**Comment by xeluna** [comment]
Okay, I can put a placeholder in the meantime.
